/** The landing page's own words, where the markup is not static. Name the work. Do not coach. */
export const landing = {
  signIn: 'Log in',
  waitlist: 'Join the waitlist',
  waitlistJoin: 'Join',
  waitlistJoined: 'Joined.',
  waitlistThanks: "Thanks for joining the waitlist! We'll send you an email when this app is fully ready for you.",
  waitlistNeed: 'Type an email.',
  waitlistFail: 'Could not save this.',
  open: 'Open the course',
  typePassword: 'Type the password.',
  wrong: 'Wrong password.',
  unset: 'Password is not set.',
  offline: 'No connection.',
  right: 'Right.',
  pasteOff: 'Paste is off here. Type it.',
  check: 'Check',
  hear: 'Hear',
  slower: 'Slower',
  continue: 'Continue',
  next: 'Next card',
}
