/** The landing page's own words, where the markup is not static. Name the work. Do not coach. */
export const landing = {
  signIn: 'Log in',
  waitlist: 'Join the waitlist',
  waitlistJoin: 'Join',
  waitlistJoined: 'Joined.',
  waitlistThanks: 'Thanks. One email goes to this address when the course opens.',
  waitlistNeed: 'Type an email.',
  waitlistCheck: 'Check the address, like name@gmail.com.',
  waitlistBusy: 'Too many sign-ups from this network. Try again in a minute.',
  waitlistFail: 'Could not save this.',
  open: 'Open the course',
  typeEmail: 'Type an email.',
  typePassword: 'Type the password.',
  wrong: 'Wrong email or password.',
  newPassword: 'New password',
  setPassword: 'Set password',
  setFail: 'Could not set this password. Send a new link.',
  linkSpent: 'The link no longer works. Send a new one.',
  resetSent: 'Check your email for the link.',
  resetFail: 'Could not send this.',
  couldNot: 'Could not sign in.',
  unset: 'Password is not set.',
  offline: 'No connection.',
  right: 'Right.',
  pasteOff: 'Paste is off here. Type it.',
  check: 'Check',
  hear: 'Hear',
  slower: 'Slower',
  continue: 'Continue',
  next: 'Next card',
}
