import type { LevelMeta } from '../types'

export const SCRIPT_LEVELS: LevelMeta[] = [
  {
    n: 0,
    title: 'The page',
    rom: 'nâang',
    thai: 'หน้า',
    blurb: 'A consonant is a seat. A vowel is a mark that sits on it. First, the empty seat and the long aa you already say in maa.',
    focus: ['อ. A silent seat.', 'า. Sits after, long aa.', 'อา. อ plus า.'],
    min: 3,
  },
  {
    n: 1,
    title: 'ม and มา',
    rom: 'mɔɔ maa',
    thai: 'มา',
    blurb: 'ม is the letter m. Put า after it and you can read a word you already know: มา, come.',
    focus: ['ม. The letter m.', 'มา. ม plus า. maa, come.'],
    min: 2,
  },
  {
    n: 2,
    title: 'A mark for tone',
    rom: 'mâi too',
    thai: 'ม้า',
    blurb: 'The wiggle lives on ม้า, the horse you already know. No mark on มา is the mid tone you already say. Learn the mark on the word, not as a card of its own.',
    focus: ['ม้า. ม plus ้ plus า. máa, horse.', 'มา. No mark. The mid tone you already say.'],
    min: 1,
  },
  {
    n: 3,
    title: 'ก and ไก่',
    rom: 'gɔɔ gài',
    thai: 'ไก่',
    blurb: 'ก is g. ไ is a vowel that sits to the left. Together they write ไก่, the chicken you already know, and กิน, eat.',
    focus: ['ก. The letter g.', 'ไ. A vowel that sits to the left.', 'ไก่, กิน, เก่า. gài, gin, gào.'],
    min: 4,
  },
  {
    n: 4,
    title: 'ไม่ and ไหม',
    rom: 'mâi mái',
    thai: 'ไม่',
    blurb: 'The mai family you already hear. ไ and ใ are two letters for the same vowel. The shapes are different. The words you know decide which one.',
    focus: ['ไม่. mâi, not.', 'ไหม. mái, the question.', 'ใหม่. mài, new.'],
    min: 4,
  },
  {
    n: 5,
    title: 'คน and ไข่',
    rom: 'kon kài',
    thai: 'คน',
    blurb: 'ค and ข both meet English k, and you already know คน and ไข่. The shapes are the next thing to attach.',
    focus: ['ค. คน, kon.', 'ข. ไข่, kài.', 'ก. Still g.'],
    min: 6,
  },
  {
    n: 6,
    title: 'ไป and ยา',
    rom: 'bpai yaa',
    thai: 'ไป',
    blurb: 'ป is bp. ย is y. Words you already say: ไป, ยา, อย่า, ย่า.',
    focus: ['ป. ไป, bpai.', 'ย. ยา, yaa.', 'อย่า, ย่า. yàa, yâa.'],
    min: 6,
  },
  {
    n: 7,
    title: 'ตา and ข้าว',
    rom: 'dtaa kâao',
    thai: 'ตา',
    blurb: 'ต is dt. ข plus า plus ว is ข้าว, rice. More words you already have, now as shapes.',
    focus: ['ต. ตา, dtaa.', 'ข้าว. kâao, rice.', 'เข้า. kâo, enter.'],
    min: 6,
  },
  {
    n: 8,
    title: 'ห as a helper',
    rom: 'hɔ̌ɔ',
    thai: 'หมา',
    blurb: 'ห can sit in front to change the tone. หมา is the dog you already know. The extra letter is not an extra sound.',
    focus: ['ห. Can sit in front to change the tone.', 'หมา. mǎa, dog.', 'No extra h sound.'],
    min: 6,
  },
  {
    n: 9,
    title: 'น ด บ',
    rom: 'nɔɔn duu bâan',
    thai: 'นอนดูบ้าน',
    blurb: 'น ด บ as seats. นอน, ดู, บ้าน.',
    focus: ['น. นอน, nɔɔn.', 'ด. ดู, duu.', 'บ. บ้าน, bâan.'],
    min: 6,
  },
  {
    n: 10,
    title: 'ง จ ช',
    rom: 'ngaan jai chái',
    thai: 'งานใจใช้',
    blurb: 'ง at the start. จ and ช, the pair you already hear as j and ch.',
    focus: ['ง. งาน, ngaan.', 'จ. ใจ, jai.', 'ช. ใช้, chái.'],
    min: 6,
  },
  {
    n: 11,
    title: 'ร ล ส',
    rom: 'rɔɔ lên sà-baai',
    thai: 'รอเล่นสบาย',
    blurb: 'ร ล ส on words you already say.',
    focus: ['ร. รอ, rɔɔ.', 'ล. เล่น, lên.', 'ส. สบาย, sà-baai.'],
    min: 6,
  },
  {
    n: 12,
    title: 'ฟ พ ภ',
    rom: 'fang pụ̂an paa-sǎa',
    thai: 'ฟังเพื่อนภาษา',
    blurb: 'ฟ พ ภ. Three letters, two sounds you already use.',
    focus: ['ฟ. ฟัง, fang.', 'พ. เพื่อน, pụ̂an.', 'ภ. ภาษา, paa-sǎa.'],
    min: 6,
  },
  {
    n: 13,
    title: 'ว and อ as vowels',
    rom: 'kâao ao',
    thai: 'ข้าวเอา',
    blurb: 'ว can close a vowel. อ can carry a vowel with no consonant sound.',
    focus: ['ว in ข้าว. The ao you already say.', 'เอา. อ plus เ. ao, take.'],
    min: 4,
  },
  {
    n: 14,
    title: 'Marks above and below',
    rom: 'gin dii sụ́ụ',
    thai: 'กินดีซื้อ',
    blurb: 'ิ ี ึ ื sit above. ุ ู sit below.',
    focus: ['ิ. กิน, gin.', 'ี. ดี, dii.', 'ื. ซื้อ, sụ́ụ.', 'ู. ดู, duu.'],
    min: 8,
  },
  {
    n: 15,
    title: 'Short a and the front vowels',
    rom: 'bpen náam pεεng',
    thai: 'เป็นน้ำแพง',
    blurb: 'ะ ั ำ, and เ แ โ sitting to the left.',
    focus: ['ะ. เป็น, bpen.', 'ำ. น้ำ, náam.', 'แ. แพง, pεεng.', 'โ. โทร, too.'],
    min: 8,
  },
  {
    n: 16,
    title: 'The last tone marks',
    rom: 'dtǔa',
    thai: 'ตั๋ว',
    blurb: '๋ on ตั๋ว. ่ and ้ you already know on ไม่ and ม้า. No mark is a card of its own.',
    focus: ['ตั๋ว. dtǔa, ticket.', 'ไม่. ่ you already know.', 'ม้า. ้ you already know.'],
    min: 4,
  },
  {
    n: 17,
    title: 'Live and dead',
    rom: 'maa mǎa',
    thai: 'มาหมา',
    blurb: 'มา is live: mid. หมา is live with ห: rising. กิน is dead: the short vowel plus น keeps a low tone on ก.',
    focus: ['มา. Live, mid.', 'หมา. ห changes the class.', 'กิน. Dead syllable, low.'],
    min: 5,
  },
  {
    n: 18,
    title: 'Clusters',
    rom: 'glàp glâi',
    thai: 'กลับใกล้',
    blurb: 'Two consonants before the vowel. กรุงเทพ, กลับ, ใกล้.',
    focus: ['กร. กรุงเทพ.', 'กล. กลับ, ใกล้.'],
    min: 5,
  },
  {
    n: 19,
    title: 'The leftover seats',
    rom: 'tǔng tam',
    thai: 'ถึงทำ',
    blurb: 'ถ ท ศ ษ ธ ฮ. Same sounds you already say, more shapes.',
    focus: ['ถ. ถึง, tǔng.', 'ท. ทำ, tam.', 'ศ. ประเทศ.', 'ษ. ภาษา.', 'ธ. พฤหัส.', 'ฮ. Rare. The letter hɔɔ.'],
    min: 8,
  },
]
