import type { LevelMeta } from '../types'

export const SCRIPT_LEVELS: LevelMeta[] = [
  {
    n: 0,
    title: 'The page',
    rom: 'nâang',
    thai: 'หน้า',
    blurb: 'A consonant is a seat. A vowel is a mark that sits on it. First, the empty seat and the long aa you already say in maa.',
    focus: ['อ. A silent seat.', 'า. Sits after, long aa.', 'อา. อ plus า.'],
    min: 3,
  },
  {
    n: 1,
    title: 'ม and มา',
    rom: 'mɔɔ maa',
    thai: 'มา',
    blurb: 'ม is the letter m. Put า after it and you can read a word you already know: มา, come.',
    focus: ['ม. The letter m.', 'มา. ม plus า. maa, come.'],
    min: 2,
  },
  {
    n: 2,
    title: 'A mark for tone',
    rom: 'mâi too',
    thai: 'ม้า',
    blurb: 'The wiggle lives on ม้า, the horse you already know. No mark on มา is the mid tone you already say. Learn the mark on the word, not as a card of its own.',
    focus: ['ม้า. ม plus ้ plus า. máa, horse.', 'มา. No mark. The mid tone you already say.'],
    min: 1,
  },
  {
    n: 3,
    title: 'ก and ไก่',
    rom: 'gɔɔ gài',
    thai: 'ไก่',
    blurb: 'ก is g. ไ is a vowel that sits to the left. Together they write ไก่, the chicken you already know.',
    focus: ['ก. The letter g.', 'ไ. A vowel that sits to the left.', 'ไก่. gài.'],
    min: 3,
  },
  {
    n: 4,
    title: 'ไม่ and ไหม',
    rom: 'mâi mái',
    thai: 'ไม่',
    blurb: 'The mai family you already hear. ไ and ใ are two letters for the same vowel. ห in front of ม is silent: it only changes the tone.',
    focus: ['ไม่. mâi, not.', 'ห. Silent in front, changes the tone.', 'ไหม. mái, the question.', 'ใ. The other ai. ใหม่, mài.'],
    min: 6,
  },
  {
    n: 5,
    title: 'คน and ไข่',
    rom: 'kon kài',
    thai: 'คน',
    blurb: 'ค and ข both meet English k, and you already know คน and ไข่. น ends คน. เ sits to the left in เขา and เข้า.',
    focus: ['ค. คน, kon.', 'น. The n at the end of คน.', 'ข. ไข่, kài.', 'เ. Sits to the left. เขา, เข้า.'],
    min: 8,
  },
  {
    n: 6,
    title: 'ไป and ยา',
    rom: 'bpai yaa',
    thai: 'ไป',
    blurb: 'ป is bp. ย is y. Words you already say: ไป, ยา, อย่า, ย่า.',
    focus: ['ป. ไป, bpai.', 'ย. ยา, yaa.', 'อย่า, ย่า. yàa, yâa.'],
    min: 6,
  },
  {
    n: 7,
    title: 'ตา and ข้าว',
    rom: 'dtaa kâao',
    thai: 'ตา',
    blurb: 'ต is dt. ข plus า plus ว is ข้าว, rice. More words you already have, now as shapes.',
    focus: ['ต. ตา, dtaa.', 'ข้าว. kâao, rice.', 'เข้า. kâo, enter.'],
    min: 6,
  },
  {
    n: 8,
    title: 'ห, helper and letter',
    rom: 'mǎa hâi',
    thai: 'หมาให้',
    blurb: 'ห in front of ม is silent: หมา is the dog you already know. On its own it is h: ให้, หา, ห้า, หก.',
    focus: ['หมา. mǎa, dog. Silent ห.', 'ให้, หา, ห้า. ห as h.', 'หก. No vowel written, a short o is understood.'],
    min: 5,
  },
  {
    n: 9,
    title: 'น ด บ',
    rom: 'nɔɔn duu bâan',
    thai: 'นอนดูบ้าน',
    blurb: 'นอน with อ as the vowel in the middle. ด and บ as new seats. ู sits below in ดู.',
    focus: ['นอน. อ in the middle is ɔɔ.', 'ด. ดู, duu. ู below.', 'บ. บ้าน, bâan.'],
    min: 6,
  },
  {
    n: 10,
    title: 'ง จ ช',
    rom: 'ngaan jai chái',
    thai: 'งานใจใช้',
    blurb: 'ง at the start. จ and ช, the pair you already hear as j and ch.',
    focus: ['ง. งาน, ngaan.', 'จ. ใจ, jai.', 'ช. ใช้, chái.'],
    min: 6,
  },
  {
    n: 11,
    title: 'ร ล ส',
    rom: 'rɔɔ lên sà-baai',
    thai: 'รอเล่นสบาย',
    blurb: 'ร ล ส on words you already say.',
    focus: ['ร. รอ, rɔɔ.', 'ล. เล่น, lên.', 'ส. สบาย, sà-baai.'],
    min: 6,
  },
  {
    n: 12,
    title: 'ฟ พ ภ',
    rom: 'fang pụ̂an paa-sǎa',
    thai: 'ฟังเพื่อนภาษา',
    blurb: 'ฟ พ ภ. Three letters, two sounds you already use. ั sits above in ฟัง. ษ is the s inside ภาษา.',
    focus: ['ฟ. ฟัง, fang. ั above.', 'พ. พ่อ, pɔ̂ɔ.', 'ภ. ภาษา, paa-sǎa.', 'ษ. The s in ภาษา.'],
    min: 8,
  },
  {
    n: 13,
    title: 'ว and อ as vowels',
    rom: 'kâao ao',
    thai: 'ข้าวเอา',
    blurb: 'ว can close a vowel. อ can carry a vowel with no consonant sound. เ plus า around a consonant is ao.',
    focus: ['ว in ข้าว. The ao you already say.', 'เอา. อ plus เ. ao, take.', 'เก่า, เรา. gào, rao.'],
    min: 4,
  },
  {
    n: 14,
    title: 'Marks above and below',
    rom: 'gin dii sụ́ụ',
    thai: 'กินดีซื้อ',
    blurb: 'Three vowel marks that sit above the consonant: the i in กิน, the ii in ดี, the ụụ in ซื้อ. ซ is another s.',
    focus: ['ิ. กิน, gin.', 'ี. ดี, dii.', 'ซ. Another s.', 'ื. ซื้อ, sụ́ụ.'],
    min: 8,
  },
  {
    n: 15,
    title: 'Short a and the front vowels',
    rom: 'bpen náam pεεng',
    thai: 'เป็นน้ำแพง',
    blurb: 'The stop in และ, the am in น้ำ, and two more vowels that sit to the left: the εε in แพง, the oo in โรงแรม.',
    focus: ['ะ. และ, lέ.', 'ำ. น้ำ, náam.', 'แ. แพง, pεεng.', 'โ. โรงแรม, roong-rεεm.'],
    min: 8,
  },
  {
    n: 16,
    title: 'The last tone marks',
    rom: 'dtǔa',
    thai: 'ตั๋ว',
    blurb: '๋ on ตั๋ว. ่ and ้ you already know on ไม่ and ม้า. No mark is a card of its own.',
    focus: ['ตั๋ว. dtǔa, ticket.', 'ไม่. ่ you already know.', 'ม้า. ้ you already know.'],
    min: 4,
  },
  {
    n: 17,
    title: 'Live and dead',
    rom: 'maa mǎa',
    thai: 'มาหมา',
    blurb: 'มา is live: mid. หมา is live with ห: rising. กิน is dead: the short vowel plus น keeps a low tone on ก.',
    focus: ['มา. Live, mid.', 'หมา. ห changes the class.', 'กิน. Dead syllable, low.'],
    min: 5,
  },
  {
    n: 18,
    title: 'Clusters',
    rom: 'krai glàp',
    thai: 'ใครกลับ',
    blurb: 'Two consonants before the vowel. ใคร, กลับ, ใกล้, ครับ. And ุ, the short u that sits below.',
    focus: ['คร. ใคร, ครับ.', 'กล. กลับ, ใกล้, ไกล.', 'ุ. สนุก.'],
    min: 7,
  },
  {
    n: 19,
    title: 'The leftover seats',
    rom: 'tǔng tam',
    thai: 'ถึงทำ',
    blurb: 'ถ ท ศ ธ ฮ. Same sounds you already say, more shapes. And ึ, the short ụ in ถึง.',
    focus: ['ถ. ถึง, tǔng.', 'ึ. Short ụ, sits above.', 'ท. ทำ, กรุงเทพ.', 'ศ. ประเทศ.', 'ธ. ธนาคาร.', 'ฮ. Rare. The letter hɔɔ.'],
    min: 8,
  },
  {
    n: 20,
    title: 'Short and stopped',
    rom: 'bpen kε̌ng',
    thai: 'เป็นแข็ง',
    blurb: 'A small mark above shortens the vowel: เป็น, เห็น, แข็ง. The last tone mark, the high one, sits on โต๊ะ and ตุ๊กตุ๊ก.',
    focus: ['็. เป็น, เห็น, แข็ง.', '๊. โต๊ะ, ตุ๊กตุ๊ก.', 'ะ after โ. โต๊ะ stops short.'],
    min: 6,
  },
  {
    n: 21,
    title: 'เรียน',
    rom: 'rian',
    thai: 'เรียน',
    blurb: 'Vowels written in more than one piece around the consonant. One in เรียน, one in เพื่อน, one in ตัว, one in เธอ. The first half of เรียนเก่ง is here.',
    focus: ['เ◌ีย. เรียน.', 'เ◌ือ. เพื่อน, เมือง.', '◌ัว. ตัว, ครัว.', 'เ◌อ. เธอ, เจอ.'],
    min: 10,
  },
  {
    n: 22,
    title: 'ผ ฝ ฉ',
    rom: 'pǒm fǒn chǎn',
    thai: 'ผมฝนฉัน',
    blurb: 'Three high-class letters you say every day. ผม, ฝน, ฉัน.',
    focus: ['ผ. ผม, ผ้า, เผ็ด.', 'ฝ. ฝน, ฝรั่ง.', 'ฉ. ฉัน, ฉลาด.'],
    min: 9,
  },
  {
    n: 23,
    title: 'ญ ณ ฆ',
    rom: 'yǐng kun mêek',
    thai: 'หญิงคุณเมฆ',
    blurb: 'Older shapes for sounds you already read. ญ in ผู้หญิง and ใหญ่. ณ at the end of คุณ. ฆ in เมฆ.',
    focus: ['ญ. ผู้หญิง, ใหญ่.', 'ณ. คุณ.', 'ฆ. เมฆ.'],
    min: 6,
  },
  {
    n: 24,
    title: 'From Sanskrit',
    rom: 'rát-tà-baan',
    thai: 'รัฐบาล',
    blurb: 'ฐ ฏ ฎ ฬ came in with Sanskrit and Pali. ฤ is a vowel that stands on its own. รัฐบาล, ปฏิเสธ, กฎ, กีฬา, พฤหัส.',
    focus: ['ฐ. รัฐบาล.', 'ฏ. ปฏิเสธ.', 'ฎ. กฎ.', 'ฬ. กีฬา.', 'ฤ. พฤหัส, อังกฤษ.'],
    min: 10,
  },
  {
    n: 25,
    title: 'The silent tail',
    rom: 'gaa-ran',
    thai: 'การันต์',
    blurb: 'Three marks that are not sounds. One silences the letter under it, as in โทรศัพท์. ๆ says the word twice. ฯ cuts a long name short.',
    focus: ['์. โทรศัพท์, เบียร์, จันทร์.', 'ๆ. ช้าๆ.', 'ฯ. กรุงเทพฯ.'],
    min: 6,
  },
  {
    n: 26,
    title: 'The rare and the retired',
    rom: 'hâa dtua',
    thai: 'ห้าตัว',
    blurb: 'ฑ ฒ ฌ are rare. ฃ ฅ are retired. With these five you have all forty-four consonants.',
    focus: ['ฑ ฒ. Both th.', 'ฌ. ch.', 'ฃ ฅ. Retired k.'],
    min: 5,
  },
  {
    n: 27,
    title: 'Numbers on the page',
    rom: 'lêek tai',
    thai: 'เลขไทย',
    blurb: '๐ to ๙. The numbers you already count, in Thai digits. Temples and tickets still use them.',
    focus: ['๐ ๑ ๒ ๓ ๔.', '๕ ๖ ๗ ๘ ๙.'],
    min: 10,
  },
]
