/**
 * Ids are `${prefix}:${rom}`, so correcting a romanization renames the entry.
 * Saved progress is keyed by id, so a rename would orphan the card's history.
 * This maps every id retired by the romanization pass onto its replacement.
 * Applied on load and on import; see `src/storage/import.ts`.
 *
 * `w:châi rɔ̀k` is deliberately absent: ใช่หรอก was removed, not renamed.
 */
export const ID_ALIASES: Record<string, string> = {
  'i:jai dàm': 'i:jai dam',
  'i:plɔ̀ɔp jai nɔ̀i': 'i:bplɔ̀ɔp jai nɔ̀i',
  'p:ao nát lέεo': 'p:nát lέεo',
  'p:bpai bàa nít-nɔ̀i': 'p:bpai baa nít-nɔ̀i',
  'p:bpai dtàang prà-têet': 'p:bpai dtàang bprà-têet',
  'p:bɔ̀ɔk bpen prà-yòok': 'p:bɔ̀ɔk bpen bprà-yòok',
  'p:dtàam tîi kun bɔ̀ɔk': 'p:dtaam tîi kun bɔ̀ɔk',
  'p:dtòk sɔ̌ɔp': 'p:sɔ̀ɔp dtòk',
  'p:dtɔ̂ng tam-ngaan náan': 'p:dtɔ̂ng tam-ngaan naan',
  'p:dôoi rót fai': 'p:dooi rót fai',
  'p:fan jèp': 'p:bpùat fan',
  'p:gìi moong jà bpai': 'p:jà bpai gìi moong',
  'p:in-təə-nét dtòk': 'p:in-təə-nét chái mâi dâi',
  'p:jà bpai prung-níi': 'p:jà bpai prûng-níi',
  'p:jà sɔ̌ɔp prung-níi': 'p:jà sɔ̀ɔp prûng-níi',
  'p:kâo jai táng prà-yòok': 'p:kâo jai táng bprà-yòok',
  'p:kâp bpai': 'p:káp bpai',
  'p:kǎo bpen krùu': 'p:kǎo bpen kruu',
  'p:kɔ̌ɔ laa wan nụ̀ng': 'p:kɔ̌ɔ laa nụ̀ng wan',
  'p:maa rɔ̀k': 'p:mâi maa rɔ̀k',
  'p:mii lóm mâak': 'p:mii lom mâak',
  'p:mii sǐi ụ̂ụn mái': 'p:mii sǐi ụ̀ụn mái',
  'p:mii sǔan lót mái': 'p:mii sùan lót mái',
  'p:mii tɔɔn mái': 'p:mii ngən tɔɔn mái',
  'p:mâi dtɔ̂ng pûut pεεng': 'p:mâi dtɔ̂ng pûut yâak',
  'p:nám jai mâak': 'p:mii nám jai mâak',
  'p:nîi tâo-rài bàat': 'p:nîi gìi bàat',
  'p:nɔ́k jàak níi': 'p:nɔ̂ɔk jàak níi',
  'p:nε̂ε nɔɔn dâi': 'p:dâi nε̂ε nɔɔn',
  'p:plɔ̀ɔp jai kun': 'p:bplɔ̀ɔp jai kun',
  'p:prung-níi pǒm wâang': 'p:prûng-níi pǒm wâang',
  'p:prà-yòok níi kâo jai ngâai': 'p:bprà-yòok níi kâo jai ngâai',
  'p:prà-yòok sɔ̌ɔng prà-yòok': 'p:bprà-yòok sɔ̌ɔng bprà-yòok',
  'p:pε̂ε à-rai': 'p:pέε à-rai',
  'p:rao nát gan prung-níi': 'p:rao nát gan prûng-níi',
  'p:rian gàp krùu': 'p:rian gàp kruu',
  'p:rụ̂ang tîi kəəi': 'p:rụ̂ang tîi kəəi lâo',
  'p:sà-baai dii jâ': 'p:sà-baai dii jâa',
  'p:sèt náan lέεo': 'p:sèt naan lέεo',
  'p:sǎm-nuan tai mâak': 'p:bpen sǎm-nuan tai',
  'p:sǐa nám jai pǒm': 'p:pǒm sǐa nám jai',
  'p:sǔan nɔ́ɔi tîi pìt': 'p:sùan nɔ́ɔi tîi pìt',
  'p:sǔan yài kâo jai': 'p:sùan yài kâo jai',
  'p:waang pεεn gan': 'p:waang pε̌εn gan',
  'p:yàa jai dàm': 'p:yàa jai dam',
  'p:yùu tεεo sì-lǒm': 'p:yùu tε̌εo sǐi-lom',
  's:sɔ́ɔ': 's:sɔɔ sôo',
  'w:bàa': 'w:baa',
  'w:dtàam nán': 'w:dtaam nán',
  'w:dtàam tîi': 'w:dtaam tîi',
  'w:dtàang prà-têet': 'w:dtàang bprà-têet',
  'w:dôoi': 'w:dooi',
  'w:gɔ̂ dtàam': 'w:gɔ̂ dtaam',
  'w:jai dàm': 'w:jai dam',
  'w:jâ': 'w:jâa',
  'w:kaan': 'w:kan',
  'w:krùu': 'w:kruu',
  'w:kâp': 'w:káp',
  'w:lóm': 'w:lom',
  'w:lóm rεεng': 'w:lom rεεng',
  'w:lûam': 'w:lǔam',
  'w:ngǔu': 'w:nguu',
  'w:náan': 'w:naan',
  'w:nɔ́k jàak': 'w:nɔ̂ɔk jàak',
  'w:paa': 'w:bpàa',
  'w:plɔ̀ɔp jai': 'w:bplɔ̀ɔp jai',
  'w:prung-níi': 'w:prûng-níi',
  'w:prà-yòok': 'w:bprà-yòok',
  'w:pɔɔm': 'w:pɔ̌ɔm',
  'w:pε̂ε': 'w:pέε',
  'w:pεεn': 'w:pε̌εn',
  'w:pεεn-tîi': 'w:pε̌εn-tîi',
  'w:sì-lǒm': 'w:sǐi-lom',
  'w:sǐi sǒm': 'w:sǐi sôm',
  'w:sǔan lót': 'w:sùan lót',
  'w:sǔan nɔ́ɔi': 'w:sùan nɔ́ɔi',
  'w:sǔan yài': 'w:sùan yài',
  'w:sɔ̌ɔp': 'w:sɔ̀ɔp',
  'w:tàang': 'w:taang',
  'w:tàang kâo': 'w:taang kâo',
  'w:tàang ɔ̀ɔk': 'w:taang ɔ̀ɔk',
  'w:táng nîi': 'w:táng níi',
  'w:tεεo': 'w:tε̌εo',
  'w:waang pεεn': 'w:waang pε̌εn',
  'w:yìam': 'w:yîam',
  'w:ún': 'w:ùn',
  'w:ụ̂ụn': 'w:ụ̀ụn',
}

/** The id an old saved item should be filed under now. */
export function currentId(id: string): string {
  return ID_ALIASES[id] ?? id
}
