/**
 * Ids are `${prefix}:${rom}`, so correcting a romanization renames the entry.
 * Saved progress is keyed by id, so a rename would orphan the card's history.
 * This maps every id retired by the romanization passes onto its replacement.
 * Applied on load and on import; see `src/storage/import.ts`.
 *
 * `w:châi rɔ̀k`, `p:pǒm chụ̂ụ luis` and `i:jai yen jai dii` are deliberately absent: they were removed, not renamed.
 */
export const ID_ALIASES: Record<string, string> = {
  'i:grεεng jai mâak': 'i:greeng jai mâak',
  'i:jai dam': 'w:jai dam',
  'i:jai dàm': 'w:jai dam',
  'i:jai kwâang': 'w:jai gwâang',
  'i:plɔ̀ɔp jai nɔ̀i': 'i:bplɔ̀ɔp jai nɔ̀i',
  'i:sǐa jai ná': 'i:sǐa jai dûai ná',
  'p:ao nát lέεo': 'p:nát lέεo',
  'p:bpai bàa nít-nɔ̀i': 'p:bpai baa nít-nɔ̀i',
  'p:bpai dtàang prà-têet': 'p:bpai dtàang bprà-têet',
  'p:bpai kâao sǎn mái': 'p:bpai kâao-sǎan mái',
  'p:bɔ̀ɔk bpen prà-yòok': 'p:bɔ̀ɔk bpen bprà-yòok',
  'p:dii ná kun': 'p:kun jai dii ná',
  'p:dtàam tîi kun bɔ̀ɔk': 'p:dtaam tîi kun bɔ̀ɔk',
  'p:dtòk sɔ̌ɔp': 'p:sɔ̀ɔp dtòk',
  'p:dtɔɔn nîi tîang': 'p:dtɔɔn níi tîang',
  'p:dtɔɔn nîi wâang': 'p:dtɔɔn níi wâang',
  'p:dtɔ̂ng tam-ngaan náan': 'p:dtɔ̂ng tam-ngaan naan',
  'p:dtὲ bɔn tîi sà-nǎam': 'p:dtè bɔn tîi sà-nǎam',
  'p:dâng nán pǒm glàp': 'p:dang nán pǒm glàp',
  'p:dôoi rót fai': 'p:dooi rót fai',
  'p:fan jèp': 'p:bpùat fan',
  'p:grεεng jai kun': 'p:greeng jai kun',
  'p:gìi moong jà bpai': 'p:jà bpai gìi moong',
  'p:gùap lụụm lέεo': 'p:gʉ̀ap lʉʉm lέεo',
  'p:in-təə-nét dtòk': 'p:in-təə-nét chái mâi dâi',
  'p:jai kwâang ná': 'p:jai gwâang ná',
  'p:jai yen jai yen': 'p:jai yen yen',
  'p:jà bpai prung-níi': 'p:jà bpai prûng-níi',
  'p:jà sɔ̌ɔp prung-níi': 'p:jà sɔ̀ɔp prûng-níi',
  'p:kun maa tǔng mʉ̂a-rai': 'p:kun maa tʉ̌ng mʉ̂a-rài',
  'p:kâo jai táng prà-yòok': 'p:kâo jai táng bprà-yòok',
  'p:kâp bpai': 'p:káp bpai',
  'p:kǎo bpen krùu': 'p:kǎo bpen kruu',
  'p:kɔ̌ɔ laa wan nụ̀ng': 'p:kɔ̌ɔ laa nʉ̀ng wan',
  'p:kε̂ε nîi tâo nán': 'p:kε̂ε níi tâo nán',
  'p:lûuk kâa maa lέεo': 'p:lûuk káa maa lέεo',
  'p:maa rɔ̀k': 'p:mâi maa rɔ̀k',
  'p:mii dtôn yài': 'p:dtôn-mái sɔ̌ɔng dtôn',
  'p:mii lóm mâak': 'p:mii lom mâak',
  'p:mii sǐi ụ̂ụn mái': 'p:mii sǐi ʉ̀ʉn mái',
  'p:mii sǔan lót mái': 'p:mii sùan lót mái',
  'p:mii tɔɔn mái': 'p:mii ngən tɔɔn mái',
  'p:mâi dtɔ̂ng pûut pεεng': 'p:mâi dtɔ̂ng pûut yâak',
  'p:nám jai mâak': 'p:mii nám jai mâak',
  'p:nîi kε̂ε nîi': 'p:ao kε̂ε níi',
  'p:nîi tâo-rài bàat': 'p:nîi gìi bàat',
  'p:nɔ́k jàak níi': 'p:nɔ̂ɔk jàak níi',
  'p:nε̂ε nɔɔn dâi': 'p:dâi nε̂ε nɔɔn',
  'p:plɔ̀ɔp jai kun': 'p:bplɔ̀ɔp jai kun',
  'p:prung-níi pǒm wâang': 'p:prûng-níi pǒm wâang',
  'p:prà-yòok níi kâo jai ngâai': 'p:bprà-yòok níi kâo jai ngâai',
  'p:prà-yòok sɔ̌ɔng prà-yòok': 'p:bprà-yòok sɔ̌ɔng bprà-yòok',
  'p:pûut dâi dtὲε yang nít-nɔ̀i': 'p:pûut dâi dtὲε yang mâi gèng',
  'p:pǒm kít tǔng bâan': 'p:pǒm kít tʉ̌ng bâan',
  'p:pε̂ε à-rai': 'p:pέε à-rai',
  'p:rao nát gan prung-níi': 'p:rao nát gan prûng-níi',
  'p:rian gàp krùu': 'p:rian gàp kruu',
  'p:rà-wàang bâan gàp ngaan': 'p:rá-wàang bâan gàp ngaan',
  'p:rụ̂ang tîi kəəi': 'p:rʉ̂ang tîi kəəi lâo',
  'p:sà-baai dii jâ': 'p:sà-baai dii jâa',
  'p:sà-rúp lέεo': 'p:sà-rùp lέεo',
  'p:sèt náan lέεo': 'p:sèt naan lέεo',
  'p:sǎm-nuan tai mâak': 'p:bpen sǎm-nuan tai',
  'p:sǐa nám jai pǒm': 'p:pǒm sǐa nám jai',
  'p:sǒng-sǎi wâa jing': 'p:sǒng-sǎi wâa jing rʉ̌ʉ bplào',
  'p:sǔan nɔ́ɔi tîi pìt': 'p:sùan nɔ́ɔi tîi pìt',
  'p:sǔan yài kâo jai': 'p:sùan yài kâo jai',
  'p:tâo-rài kráp/kâ': 'p:tâo-rài kráp/ká',
  'p:tǔng lέεo rə̌ə': 'p:tʉ̌ng lέεo rə̌ə',
  'p:waang pεεn gan': 'p:waang pε̌εn gan',
  'p:yàa grεεng jai': 'p:yàa greeng jai',
  'p:yàa jai dàm': 'p:yàa jai dam',
  'p:yùu tεεo sì-lǒm': 'p:yùu tε̌εo sǐi-lom',
  's:sɔ́ɔ': 's:sɔɔ sôo',
  's:tǔng': 's:tʉ̌ng',
  'w:bàa': 'w:baa',
  'w:dtàam nán': 'w:dtaam nán',
  'w:dtàam tîi': 'w:dtaam tîi',
  'w:dtàang prà-têet': 'w:dtàang bprà-têet',
  'w:dtɔɔn nîi': 'w:dtɔɔn níi',
  'w:dtὲ': 'w:dtè',
  'w:dâng nán': 'w:dang nán',
  'w:dôoi': 'w:dooi',
  'w:glua': 'w:glʉa',
  'w:grεεng jai': 'w:greeng jai',
  'w:gùap': 'w:gʉ̀ap',
  'w:gɔ̂ dtàam': 'w:gɔ̂ dtaam',
  'w:jai dàm': 'w:jai dam',
  'w:jai kwâang': 'w:jai gwâang',
  'w:jâ': 'w:jâa',
  'w:jùut': 'w:jʉ̀ʉt',
  'w:kaan': 'w:kan',
  'w:kom-piw-dtəə': 'w:kɔm-piu-dtəə',
  'w:krùu': 'w:kruu',
  'w:kwâang': 'w:gwâang',
  'w:kài dao': 'w:kài daao',
  'w:kâao sǎn': 'w:kâao-sǎan',
  'w:kâp': 'w:káp',
  'w:kít tǔng': 'w:kít tʉ̌ng',
  'w:kε̂ε nîi': 'w:kε̂ε níi',
  'w:lóm': 'w:lom',
  'w:lóm rεεng': 'w:lom rεεng',
  'w:lûam': 'w:lǔam',
  'w:lûuk kâa': 'w:lûuk káa',
  'w:mʉ̂a-rai': 'w:mʉ̂a-rài',
  'w:ngǔu': 'w:nguu',
  'w:náan': 'w:naan',
  'w:nák dtὲ': 'w:nák dtè',
  'w:nɔ́k jàak': 'w:nɔ̂ɔk jàak',
  'w:paa': 'w:bpàa',
  'w:plɔ̀ɔp jai': 'w:bplɔ̀ɔp jai',
  'w:prung-níi': 'w:prûng-níi',
  'w:prà-yòok': 'w:bprà-yòok',
  'w:pɔɔm': 'w:pɔ̌ɔm',
  'w:pε̂ε': 'w:pέε',
  'w:pεεn': 'w:pε̌εn',
  'w:pεεn-tîi': 'w:pε̌εn-tîi',
  'w:pὲεn': 'w:pὲn',
  'w:rà-wàang': 'w:rá-wàang',
  'w:soi': 'w:sɔɔi',
  'w:sà-dtang': 'w:sà-dtaang',
  'w:sà-pǎan': 'w:sà-paan',
  'w:sà-rúp': 'w:sà-rùp',
  'w:sì-lǒm': 'w:sǐi-lom',
  'w:sǐi nám dtaan': 'w:sǐi náam dtaan',
  'w:sǐi nám ngəən': 'w:sǐi nám ngən',
  'w:sǐi sǒm': 'w:sǐi sôm',
  'w:sǔan lót': 'w:sùan lót',
  'w:sǔan nɔ́ɔi': 'w:sùan nɔ́ɔi',
  'w:sǔan yài': 'w:sùan yài',
  'w:sɔ̌ɔp': 'w:sɔ̀ɔp',
  'w:tàang': 'w:taang',
  'w:tàang kâo': 'w:taang kâo',
  'w:tàang ɔ̀ɔk': 'w:taang ɔ̀ɔk',
  'w:táng nîi': 'w:táng níi',
  'w:tǔng': 'w:tʉ̌ng',
  'w:tɔ̀ɔ': 'w:dtɔ̀ɔ',
  'w:tɔ̀ɔ rɔɔng': 'w:dtɔ̀ɔ rɔɔng',
  'w:tεεo': 'w:tε̌εo',
  'w:waang pεεn': 'w:waang pε̌εn',
  'w:yìam': 'w:yîam',
  'w:ún': 'w:ùn',
  'w:ụ̂ụn': 'w:ʉ̀ʉn',
  'w:ὲεp': 'w:έp',
}

/** The id an old saved item should be filed under now. Dotted u folds onto ʉ. */
export function currentId(id: string): string {
  return (ID_ALIASES[id] ?? id).replaceAll('ụ', 'ʉ')
}
