import type { LevelMeta } from './types'

export const LEVELS: LevelMeta[] = [
  {
    n: 0,
    title: 'The sound system',
    rom: 'sǐang',
    thai: 'เสียง',
    blurb: 'Five tones. Long and short vowels. g/k, bp/p, dt/t.',
    focus: [
      'maa, máa, mǎa. Come, horse, dog. Mid, high, rising.',
      'mâi, mài, mái. Not, new, and the question.',
      'kâo vs kâao. Enter versus rice. Short and long are different words.',
      'g/k, bp/p, dt/t, j/ch. Stops English writes as one letter.',
      'ε, ɔ, ə, ụ. Vowels English does not write.',
    ],
    min: 36,
  },
  {
    n: 1,
    title: 'Survival',
    rom: 'sà-wàt-dii',
    thai: 'สวัสดี',
    blurb: 'Hello, the polite endings, and numbers to ten.',
    focus: [
      'kráp / kâ. Polite endings, by who is speaking.',
      'pǒm, chǎn, kun. I (male), I (female), and you.',
      'châi / mâi châi. Yes, and not so.',
      'Numbers 1 to 10.',
    ],
    min: 40,
  },
  {
    n: 2,
    title: 'Core verbs',
    rom: 'bpai maa',
    thai: 'ไปมา',
    blurb: 'Subject, verb, object. No conjugation, no plurals, no articles.',
    focus: [
      'Subject, verb, object. Thai keeps this order.',
      'mâi + verb. That is how you say no.',
      'kǎo, rao, pûak-kǎo. He or she, we, they.',
    ],
    min: 44,
  },
  {
    n: 3,
    title: 'Questions',
    rom: 'tam-mai',
    thai: 'ทำไม',
    blurb: 'Question words sit where the answer would sit. Yes/no needs only mái.',
    focus: [
      '… mái? A yes or no question.',
      '… rụ̌ụ bplào? Or not.',
      'à-rai, tîi-nǎi, mụ̂a-rai, tam-mai, krai, yang-ngai, tâo-rài, gìi. Question words sit where the answer would sit.',
    ],
    min: 40,
  },
  {
    n: 4,
    title: 'Food and drink',
    rom: 'gin kâao',
    thai: 'กินข้าว',
    blurb: 'Ordering, tasting, refusing chilli.',
    focus: [
      'ao … nɔ̀i. I will have a little, the way you order.',
      'mâi pèt. Not spicy.',
      'gèp dtang. The bill.',
      'Dishes and tastes.',
    ],
    min: 54,
  },
  {
    n: 5,
    title: 'Numbers, money, time',
    rom: 'gìi moong',
    thai: 'กี่โมง',
    blurb: 'Counting to a million, paying in baht, and the six-hour Thai clock.',
    focus: [
      'sìp, rɔ́ɔi, pan, mụ̀ụn, sε̌εn, láan. Ten through a million.',
      'moong, tûm, dtii. The six-hour clock.',
      'Days and months.',
    ],
    min: 54,
  },
  {
    n: 6,
    title: 'Getting around',
    rom: 'bpai tîi-nǎi',
    thai: 'ไปที่ไหน',
    blurb: 'Taxis, the BTS, left, right, straight. The glai / glâi trap.',
    focus: [
      'líao sáai / kwǎa. Turn left, turn right.',
      'dtrong bpai. Straight on.',
      'jɔ̀ɔt. Stop, as you tell a taxi.',
      'glai vs glâi. Far versus near.',
    ],
    min: 48,
  },
  {
    n: 7,
    title: 'Time and aspect',
    rom: 'dtɔɔn nîi',
    thai: 'ตอนนี้',
    blurb: 'Now, just now, and not yet. Chiang Mai is in this lesson.',
    focus: [
      'dtɔɔn, dtɔɔn nîi. When, and now.',
      'pə̂ng. Just now.',
      'yang mâi. Not yet.',
      'gam-lang, kəəi. In the middle of, and ever.',
      'chiang-mài. Chiang Mai.',
    ],
    min: 44,
  },
  {
    n: 8,
    title: 'Wanting and needing',
    rom: 'yàak',
    thai: 'อยาก',
    blurb: 'Modals: want, must, should, can, may. Three different cans.',
    focus: [
      'yàak, dtɔ̂ng, kuan. Want, must, should.',
      'dâi, bpen, wǎi. Three different cans.',
      'lɔɔng. Try.',
    ],
    min: 40,
  },
  {
    n: 9,
    title: 'People and describing',
    rom: 'krɔ̂ɔp-krua',
    thai: 'ครอบครัว',
    blurb: 'Family, friends, what people are like. Classifiers appear.',
    focus: [
      'kon, an, dtua. Classifiers for people, things, animals.',
      'The adjective follows the noun.',
      'pîi / nɔ́ɔng. Older and younger.',
    ],
    min: 54,
  },
  {
    n: 10,
    title: 'Home and routine',
    rom: 'bâan',
    thai: 'บ้าน',
    blurb: 'Rooms, things, and the verbs of a normal day.',
    focus: [
      'dtụ̀ụn, nɔɔn. Wake, sleep.',
      'àap náam. Bathe.',
      'sák pâa. Wash clothes.',
      'hɔ̂ng …. The rooms of a house.',
    ],
    min: 50,
  },
  {
    n: 11,
    title: 'Shopping',
    rom: 'sụ́ụ kɔ̌ɔng',
    thai: 'ซื้อของ',
    blurb: 'Colours, sizes, bargaining softly.',
    focus: [
      'lót nɔ̀i dâi mái. Can you come down a little.',
      'sǐi …. Colours.',
      'pεεng bpai. Too expensive.',
    ],
    min: 50,
  },
  {
    n: 12,
    title: 'Feelings and health',
    rom: 'sà-baai dii mái',
    thai: 'สบายดีไหม',
    blurb: 'How you feel, what hurts, and the doctor.',
    focus: [
      'rúu-sụ̀k. How you feel.',
      'bpùai, jèp. Ill, and in pain.',
      'hǐu, ìm, nụ̀ai, bụ̀a. Hungry, full, tired, bored.',
    ],
    min: 50,
  },
  {
    n: 13,
    title: 'Work, study, tech',
    rom: 'tam ngaan',
    thai: 'ทำงาน',
    blurb: 'Meetings, phones, and the internet.',
    focus: [
      'bprà-chum. A meeting.',
      'rian, sɔ̌ɔn. Learn, teach.',
      'toorasàp, in-təə-nét. Phone and the internet.',
    ],
    min: 50,
  },
  {
    n: 14,
    title: 'Weather and Thailand',
    rom: 'fǒn dtòk',
    thai: 'ฝนตก',
    blurb: 'Rain, heat, sea, mountains, and the country itself.',
    focus: [
      'fǒn dtòk. It is raining.',
      'rɔ́ɔn, nǎao. Hot and cold.',
      'tá-lee, puu-kǎo. Sea and mountain.',
      'jang-wàt. A province.',
    ],
    min: 40,
  },
  {
    n: 15,
    title: 'Connectors',
    rom: 'prɔ́ wâa',
    thai: 'เพราะว่า',
    blurb: 'If, because, but, and, so. Relative tîi and the small words that make sentences long.',
    focus: [
      'tâa …. If.',
      'prɔ́ wâa. Because.',
      'dtὲε. But.',
      'lέ, gɔ̂, ləəi. And, then, so.',
      'tîi, wâa, hâi. The small words that make a sentence long.',
    ],
    min: 60,
  },
  {
    n: 16,
    title: 'Comparing',
    rom: 'gwàa',
    thai: 'กว่า',
    blurb: 'More, most, same, a bit, too much.',
    focus: [
      '… gwàa. More than.',
      '… tîi-sùt. The most.',
      'tâo gan. The same.',
      'nít-nɔ̀i, gəən bpai. A bit, and too much.',
    ],
    min: 36,
  },
  {
    n: 17,
    title: 'Particles and register',
    rom: 'ná',
    thai: 'นะ',
    blurb: 'The words at the end. ná, sì, kráp, kâ.',
    focus: [
      'ná, sì, rɔ̀k, lâ. Soften, insist, contradict, leave it.',
      'nɔ̀i, rɔ̀k, ləəi. A little, not at all, altogether.',
      'kráp, kâ, já. Polite, and close.',
    ],
    min: 60,
  },
  {
    n: 18,
    title: 'Bangkok life',
    rom: 'tîao',
    thai: 'เที่ยว',
    blurb: 'Going out, making plans, meeting people.',
    focus: [
      'nát. An appointment.',
      'tîao. Going out.',
      'kui. To chat.',
      'rúu-jàk. To know a person.',
    ],
    min: 50,
  },
  {
    n: 19,
    title: 'Opinion and story',
    rom: 'kít wâa',
    thai: 'คิดว่า',
    blurb: 'Saying what you think, telling what happened.',
    focus: [
      'kít wâa, rúu-sụ̀k wâa. I think, I feel.',
      'hěn dûai. I agree.',
      'dtɔɔn rε̂εk, jàak nán, sùt táai. At first, after that, in the end.',
    ],
    min: 46,
  },
  {
    n: 20,
    title: 'Heart words and idioms',
    rom: 'jai',
    thai: 'ใจ',
    blurb: 'jai yen, grεεng jai, nám jai.',
    focus: [
      'jai yen, jai rɔ́ɔn. A cool heart, a hot heart.',
      'grεεng jai. The reluctance to impose.',
      'nám jai. Kindness, a gift of the heart.',
      'tam bun. Make merit.',
    ],
    min: 54,
  },
  {
    n: 21,
    title: 'Fluency capstone',
    rom: 'pûut dâi lέεo',
    thai: 'พูดได้แล้ว',
    blurb: 'Two-sentence dictation, and proverbs.',
    focus: [
      'Two-sentence dictation. Hold a whole thought.',
      'English to Thai paragraphs.',
      'sǎm-nuan. Proverbs.',
    ],
    min: 36,
  },
]

export const LEVEL_COUNT = LEVELS.length

export function levelMeta(n: number): LevelMeta {
  const m = LEVELS[n]
  if (!m) throw new Error(`No level ${n}`)
  return m
}
