import type { LevelMeta } from './types'

export const LEVELS: LevelMeta[] = [
  {
    n: 0,
    title: 'The sound system',
    rom: 'sǐang',
    thai: 'เสียง',
    blurb: 'Five tones. Long and short vowels. g/k, bp/p, dt/t.',
    focus: [
      'maa, máa, mǎa. Come, horse, dog. Mid, high, rising.',
      'mâi, mài, mái. Not, new, and the question.',
      'kâo vs kâao. Enter versus rice. Short and long are different words.',
      'g/k, bp/p, dt/t, j/ch. Stops English writes as one letter.',
      'ε, ɔ, ə, ʉ. Vowels English does not write.',
    ],
    min: 36,
  },
  {
    n: 1,
    title: 'Survival',
    rom: 'sà-wàt-dii',
    thai: 'สวัสดี',
    blurb: 'Hello, the polite endings, and numbers to ten.',
    focus: [
      'kráp / kâ. Polite endings, by who is speaking.',
      'pǒm, chǎn, kun. I (male), I (female), and you.',
      'châi / mâi châi. Yes, and not so.',
      'Numbers 1 to 10.',
    ],
    min: 40,
  },
  {
    n: 2,
    title: 'Core verbs',
    rom: 'bpai maa',
    thai: 'ไปมา',
    blurb: 'Subject, verb, object. No conjugation, no plurals, no articles.',
    focus: [
      'Subject, verb, object. Thai keeps this order.',
      'mâi + verb. That is how you say no.',
      'kǎo, rao, pûak-kǎo. He or she, we, they.',
    ],
    min: 44,
  },
  {
    n: 3,
    title: 'Questions',
    rom: 'tam-mai',
    thai: 'ทำไม',
    blurb: 'Question words sit where the answer would sit. Yes/no needs only mái.',
    focus: [
      '… mái? A yes or no question.',
      '… rʉ̌ʉ bplào? Or not.',
      'à-rai, tîi-nǎi, mʉ̂a-rài, tam-mai, krai, yang-ngai, tâo-rài, gìi. Question words sit where the answer would sit.',
    ],
    min: 40,
  },
  {
    n: 4,
    title: 'Food and drink',
    rom: 'gin kâao',
    thai: 'กินข้าว',
    blurb: 'Ordering, tasting, refusing chilli.',
    focus: [
      'ao … nɔ̀i. I will have a little, the way you order.',
      'mâi pèt. Not spicy.',
      'gèp dtang. The bill.',
      'Dishes and tastes.',
    ],
    min: 54,
  },
  {
    n: 5,
    title: 'Numbers, money, time',
    rom: 'gìi moong',
    thai: 'กี่โมง',
    blurb: 'Counting to a million, paying in baht, and the six-hour Thai clock.',
    focus: [
      'sìp, rɔ́ɔi, pan, mʉ̀ʉn, sε̌εn, láan. Ten through a million.',
      'moong, tûm, dtii. The six-hour clock.',
      'bàai moong, sìi moong yen, nʉ̀ng tûm. 1 p.m., 4 p.m., 7 p.m.',
      'tîang, krʉ̂ng. Noon, and half past.',
      'Days of the week.',
    ],
    min: 54,
  },
  {
    n: 6,
    title: 'Getting around',
    rom: 'bpai tîi-nǎi',
    thai: 'ไปที่ไหน',
    blurb: 'Taxis, the BTS, left, right, straight. The glai / glâi trap.',
    focus: [
      'líao sáai / kwǎa. Turn left, turn right.',
      'dtrong bpai. Straight on.',
      'jɔ̀ɔt. Stop, as you tell a taxi.',
      'glai vs glâi. Far versus near.',
    ],
    min: 48,
  },
  {
    n: 7,
    title: 'Time and aspect',
    rom: 'dtɔɔn níi',
    thai: 'ตอนนี้',
    blurb: 'Now, just now, and not yet. Chiang Mai is in this lesson.',
    focus: [
      'dtɔɔn, dtɔɔn níi. When, and now.',
      'pə̂ng. Just now.',
      'yang mâi. Not yet.',
      'gam-lang, kəəi. In the middle of, and ever.',
      'chiang-mài. Chiang Mai.',
    ],
    min: 44,
  },
  {
    n: 8,
    title: 'Wanting and needing',
    rom: 'yàak',
    thai: 'อยาก',
    blurb: 'Modals: want, must, should, can, may. Three different cans.',
    focus: [
      'yàak, dtɔ̂ng, kuan. Want, must, should.',
      'dâi, bpen, wǎi. Three different cans.',
      'lɔɔng. Try.',
    ],
    min: 40,
  },
  {
    n: 9,
    title: 'People and describing',
    rom: 'krɔ̂ɔp-krua',
    thai: 'ครอบครัว',
    blurb: 'Family, friends, what people are like. Classifiers appear.',
    focus: [
      'kon, an, dtua. Classifiers for people, things, animals.',
      'The adjective follows the noun.',
      'pîi, nɔ́ɔng, bpâa, lung. Family words Thais use for you and I.',
    ],
    min: 54,
  },
  {
    n: 10,
    title: 'Home and routine',
    rom: 'bâan',
    thai: 'บ้าน',
    blurb: 'Rooms, things, and the verbs of a normal day.',
    focus: [
      'dtʉ̀ʉn, nɔɔn. Wake, sleep.',
      'àap náam. Bathe.',
      'sák pâa. Wash clothes.',
      'hɔ̂ng …. The rooms of a house.',
    ],
    min: 50,
  },
  {
    n: 11,
    title: 'Shopping',
    rom: 'sʉ́ʉ kɔ̌ɔng',
    thai: 'ซื้อของ',
    blurb: 'Colours, sizes, bargaining softly.',
    focus: [
      'lót nɔ̀i dâi mái. Can you come down a little.',
      'sǐi …. Colours.',
      'pεεng bpai. Too expensive.',
    ],
    min: 50,
  },
  {
    n: 12,
    title: 'Feelings and health',
    rom: 'sà-baai dii mái',
    thai: 'สบายดีไหม',
    blurb: 'How you feel, what hurts, and the doctor.',
    focus: [
      'rúu-sʉ̀k. How you feel.',
      'bpùai, jèp. Ill, and in pain.',
      'hǐu, ìm, nʉ̀ai, bʉ̀a. Hungry, full, tired, bored.',
    ],
    min: 50,
  },
  {
    n: 13,
    title: 'Work, study, tech',
    rom: 'tam ngaan',
    thai: 'ทำงาน',
    blurb: 'Meetings, phones, and the internet.',
    focus: [
      'bprà-chum. A meeting.',
      'rian, sɔ̌ɔn. Learn, teach.',
      'too-rá-sàp, in-təə-nét. Phone and the internet.',
    ],
    min: 50,
  },
  {
    n: 14,
    title: 'Weather and Thailand',
    rom: 'fǒn dtòk',
    thai: 'ฝนตก',
    blurb: 'Rain, heat, sea, mountains, and the country itself.',
    focus: [
      'fǒn dtòk. It is raining.',
      'rɔ́ɔn, nǎao. Hot and cold.',
      'tá-lee, puu-kǎo. Sea and mountain.',
      'jang-wàt. A province.',
    ],
    min: 40,
  },
  {
    n: 15,
    title: 'Connectors',
    rom: 'prɔ́ wâa',
    thai: 'เพราะว่า',
    blurb: 'If, because, but, and, so. Relative tîi and the small words that make sentences long.',
    focus: [
      'tâa …. If.',
      'prɔ́ wâa. Because.',
      'dtὲε. But.',
      'lέ, gɔ̂, ləəi. And, then, so.',
      'tîi, wâa, hâi. The small words that make a sentence long.',
    ],
    min: 60,
  },
  {
    n: 16,
    title: 'Comparing',
    rom: 'gwàa',
    thai: 'กว่า',
    blurb: 'More, most, same, a bit, too much.',
    focus: [
      '… gwàa. More than.',
      '… tîi-sùt. The most.',
      'tâo gan. The same.',
      'nít-nɔ̀i, gəən bpai. A bit, and too much.',
    ],
    min: 36,
  },
  {
    n: 17,
    title: 'Particles and register',
    rom: 'ná',
    thai: 'นะ',
    blurb: 'The words at the end. ná, sì, kráp, kâ.',
    focus: [
      'ná, sì, rɔ̀k, lâ. Soften, insist, contradict, leave it.',
      'nɔ̀i, rɔ̀k, ləəi. A little, not at all, altogether.',
      'kráp, kâ, já. Polite, and close.',
      'máng, tə̀, nə́, ɔ̌ɔ. A guess, a nudge, a shared view, oh I see.',
    ],
    min: 60,
  },
  {
    n: 18,
    title: 'Bangkok life',
    rom: 'tîao',
    thai: 'เที่ยว',
    blurb: 'Going out, making plans, meeting people.',
    focus: [
      'nát. An appointment.',
      'tîao. Going out.',
      'kui. To chat.',
      'rúu-jàk. To know a person.',
    ],
    min: 50,
  },
  {
    n: 19,
    title: 'Opinion and story',
    rom: 'kít wâa',
    thai: 'คิดว่า',
    blurb: 'Saying what you think, telling what happened.',
    focus: [
      'kít wâa, rúu-sʉ̀k wâa. I think, I feel.',
      'hěn dûai. I agree.',
      'dtɔɔn rε̂εk, jàak nán, sùt táai. At first, after that, in the end.',
    ],
    min: 46,
  },
  {
    n: 20,
    title: 'Heart words',
    rom: 'jai',
    thai: 'ใจ',
    blurb: 'jai yen, greeng jai, nám jai.',
    focus: [
      'jai yen, jai rɔ́ɔn. A cool heart, a hot heart.',
      'greeng jai. The reluctance to impose.',
      'nám jai. Kindness, a gift of the heart.',
      'tam bun. Make merit.',
    ],
    min: 54,
  },
  {
    n: 21,
    title: 'Talking about Thai',
    rom: 'pûut dâi lέεo',
    thai: 'พูดได้แล้ว',
    blurb: 'Words for the language itself: a word, a sentence, its meaning, a saying.',
    focus: [
      'kam, bprà-yòok, kwaam mǎai. Word, sentence, meaning.',
      'kâo jai ngâai, kâo jai yâak. Easy and hard to follow.',
      'sǎm-nuan. A saying, and the word for one.',
    ],
    min: 36,
  },
  {
    n: 22,
    title: 'Months and the calendar',
    rom: 'dʉan',
    thai: 'เดือน',
    blurb: 'The twelve months, the three seasons, and the date people write.',
    focus: [
      'má-gà-raa-kom to tan-waa-kom. The twelve months.',
      'nâa rɔ́ɔn, nâa fǒn, nâa nǎao. Hot, wet, cool. Thailand has three.',
      'wan tîi. The date, and how to ask for it.',
      'sǒng-graan, lɔɔi grà-tong. Two festivals worth the diary.',
    ],
    min: 48,
  },
  {
    n: 23,
    title: 'Relatives and counting things',
    rom: 'pîi nɔ́ɔng',
    thai: 'พี่น้อง',
    blurb: 'Thai names which side of the family a person is on, and counts nothing without a classifier.',
    focus: [
      'bpùu, yâa, dtaa, yaai. Four grandparents, four words.',
      'lung, bpâa, náa, aa. Aunts and uncles, by side and by age.',
      'pîi-chaai, nɔ́ɔng-sǎao. Brother and sister, older first.',
      'lûuk, lêm, krʉ̂ang, pὲn, lǎng, dtôn. Classifiers you have not met.',
      'Noun, number, classifier. That order, every time.',
    ],
    min: 44,
  },
  {
    n: 24,
    title: 'Errands and the city',
    rom: 'jɔɔng',
    thai: 'จอง',
    blurb: 'Booking, renting, paying, and the buildings you do it in.',
    focus: [
      'jɔɔng, châo. Book, and rent.',
      'ngən sòt, bàt, oon. Cash, card, transfer.',
      'hâang, chán, líp. The mall, the floor, the lift.',
      'rʉa, krʉ̂ang bin, win. Boat, plane, the motorbike rank.',
      'lai, έp, sà-gεεn. How most of Thailand messages.',
    ],
    min: 48,
  },
  {
    n: 25,
    title: 'Trouble and courtesy',
    rom: 'chûai dûai',
    thai: 'ช่วยด้วย',
    blurb: 'What to say when something goes wrong, and how to be decent while you say it.',
    focus: [
      'hǎai, kà-mooi, dtam-rùat. Lost, stolen, the police.',
      'tɔ́ɔng sǐa, ûak, jèp kɔɔ. What happens to a body abroad.',
      'rá-wang, an-dtà-raai, chùk-chə̌ən. Careful, dangerous, emergency.',
      'wâi. Hands together. The younger one starts it.',
      'chəən, lέεo dtὲε, dtaam sà-baai. Go ahead, up to you, as you like.',
    ],
    min: 44,
  },
  {
    n: 26,
    title: 'Jobs, football, and the small words',
    rom: 'aa-chîip',
    thai: 'อาชีพ',
    blurb: 'What people do for a living, what happens on a Saturday, and the adverbs that take the edge off a sentence.',
    focus: [
      'aa-chîip. tá-hǎan, pá-yaa-baan, châang, tá-naai.',
      'fút-bɔn. dtè, ying, chá-ná, sà-mə̌ə.',
      'gɔɔng nâa, gɔɔng lǎng, pûu rák-sǎa bprà-dtuu. The positions.',
      'mâi kɔ̂i, gʉ̀ap, bprà-maan, pɔɔ dii. Not very, almost, about, just right.',
      'baang tii, tâo nán, kɔ̂i kɔ̂i. Sometimes, only, little by little.',
    ],
    min: 52,
  },
  {
    n: 27,
    title: 'Sayings',
    rom: 'sǎm-nuan',
    thai: 'สำนวน',
    blurb: 'The proverbs Thais reach for, each with its word-for-word reading.',
    focus: [
      'náam kʉ̂n hâi rîip dtàk. Scoop while the water is high.',
      'kâo mʉang dtaa lìu dtɔ̂ng lìu dtaa dtaam. In the town of squinters, squint.',
      'châat nâa dtɔɔn bàai bàai. Next life, in the afternoon. Never.',
      'mǔu mǔu, châang man. Easy, and forget it.',
    ],
    min: 30,
  },
]

export const LEVEL_COUNT = LEVELS.length

export function levelMeta(n: number): LevelMeta {
  const m = LEVELS[n]
  if (!m) throw new Error(`No level ${n}`)
  return m
}
