/** Learner-facing chrome. Name the work. Do not coach. */
export const chrome = {
  voiceLede: 'Thai in romanization. Hear the word, then write it.',
  scriptLede: 'One letter at a time, on words you already say.',
  yoursSub: 'words you have seen',
  trackDone: 'every level cleared',
  alphabetSub: 'every letter, and the level that teaches it',
  dayTitle: 'Her day',
  daySub: 'one day in Bangkok, in her words',
  dayLede: 'One day in Bangkok, in her words. A balloon fills in when you meet its line in Voice.',
  dayAll: 'Every line of her day.',
  yoursTitle: 'Already yours',
  sitAgain: 'Sit again',
  reviewAgain: 'Review again',
  loadFailed: 'Progress did not load. Nothing was written over it.',
  savedTo: 'Saved to the account',
  notSaved: 'Not saved to the account yet.',
  sessionEnded: 'The session ended. Sign in to save to the account again.',
  keptApart: 'Cards from the other account are kept apart on this browser. They return when that account signs in.',
  eraseUnsaved: 'Erase cards on this browser and sign out? Some cards have not reached the account yet.',
  eraseSignedOut: 'Erase cards on this browser? Cards that never reached an account are gone for good.',
  loadNewer: 'A newer version of the course saved these cards. Reload the page to update.',
  continue: 'Continue',
  systemSource: 'The romanization is the Paiboon system of Benjawan Poomsan Becker.',
  meet: 'Look.',
  retype: 'Retype the romanization.',
  pick: 'Which one is this?',
  hearWhich: 'Which did you hear?',
  writeRom: 'Write the romanization.',
  writeMeaning: 'What does this mean?',
  writeHeard: 'Write what you heard.',
  toneThis: 'What tone is this syllable?',
  toneFirst: 'What tone is the first syllable?',
  emptySitting: 'This sitting is empty. Come back when a level has words.',
  typeAnswer: 'Type your answer.',
  typeIt: 'Type it.',
  hearFirst: 'Hear it first.',
  right: 'Right.',
  alsoRight: 'Also right. This card is',
  yoursEmpty: 'Clear a few cards. They will land here.',
}
