/** Learner-facing chrome. Name the work. Do not coach. */
export const chrome = {
  voiceLede: 'Thai in romanization. Hear the word, then write it.',
  scriptLede: 'One letter at a time, on words you already say.',
  yoursSub: 'words you have seen',
  trackDone: 'every level cleared',
  alphabetSub: 'every letter, and the level that teaches it',
  dayTitle: 'Her day',
  daySub: 'one day in Bangkok, in her words',
  dayLede: 'One day in Bangkok, in her words. A balloon fills in when you meet its line in Voice.',
  dayAll: 'Every line of her day.',
  continue: 'Continue',
  systemSource: 'The romanization is the Paiboon system of Benjawan Poomsan Becker.',
  meet: 'Look.',
  retype: 'Retype the romanization.',
  pick: 'Which one is this?',
  hearWhich: 'Which did you hear?',
  writeRom: 'Write the romanization.',
  writeMeaning: 'What does this mean?',
  writeHeard: 'Write what you heard.',
  toneThis: 'What tone is this syllable?',
  toneFirst: 'What tone is the first syllable?',
  emptySitting: 'This sitting is empty. Come back when a level has words.',
  typeAnswer: 'Type your answer.',
  typeIt: 'Type it.',
  hearFirst: 'Hear it first.',
  right: 'Right.',
  alsoRight: 'Also right. This card is',
  yoursEmpty: 'Clear a few cards. They will land here.',
}
