/** Learner-facing chrome. Name the work. Do not coach. */
export const chrome = {
  voiceLede: 'Thai in romanization. Hear the word, then write it.',
  scriptLede: 'One letter at a time, on words you already say.',
  yoursSub: 'words you have seen',
  trackDone: 'every level cleared',
  alphabetSub: 'every letter, and where it is taught',
  systemSource: 'The romanization is adapted from the Paiboon system of Benjawan Poomsan Becker. It writes ụ where Paiboon writes ʉ.',
  meet: 'Look.',
  retype: 'Retype the romanization.',
  pick: 'Which one is this?',
  hearWhich: 'Which did you hear?',
  writeRom: 'Write the romanization.',
  writeMeaning: 'What does this mean?',
  writeHeard: 'Write what you heard.',
  toneThis: 'What tone is this syllable?',
  toneFirst: 'What tone is the first syllable?',
  emptySitting: 'This sitting is empty. Come back when a level has words.',
  typeAnswer: 'Type your answer.',
  typeIt: 'Type it.',
  hearFirst: 'Hear it first.',
  right: 'Right.',
  yoursEmpty: 'Clear a few cards. They will land here.',
}
