import { phrases } from '../build'

export default phrases(9, [
  ['krɔ̂ɔp-krua pǒm', 'ครอบครัวผม', ['my family']],
  ['nîi pɔ̂ɔ pǒm', 'นี่พ่อผม', ['this is my father', 'this is my dad']],
  ['nîi mε̂ε pǒm', 'นี่แม่ผม', ['this is my mother', 'this is my mum']],
  ['pǒm mii pîi sǎam kon', 'ผมมีพี่สามคน', ['I have three older siblings']],
  ['kǎo bpen kon jai dii', 'เขาเป็นคนใจดี', ['he is kind', 'she is kind']],
  ['dèk kon níi nâa rák', 'เด็กคนนี้น่ารัก', ['this child is cute']],
  ['gǔai-dtǐao duu nâa gin', 'ก๋วยเตี๋ยวดูน่ากิน', ['the noodles look tasty', 'the noodles look good']],
  ['kun mii lûuk mái', 'คุณมีลูกไหม', ['do you have children', 'do you have kids']],
  ['pûu-chaai kon nán sǔung', 'ผู้ชายคนนั้นสูง', ['that man is tall']],
  ['kǎo lɔ̀ɔ mâak', 'เขาหล่อมาก', ['he is very handsome']],
  ['təə sǔai', 'เธอสวย', ['she is beautiful']],
  ['rao bpen pʉ̂an gan', 'เราเป็นเพื่อนกัน', ['we are friends']],
  ['kon gὲε kon níi', 'คนแก่คนนี้', ['this old person', 'this elderly person']],
  ['chɔ̂ɔp kon ngîap', 'ชอบคนเงียบ', ['I like quiet people']],
  ['an níi sǔai', 'อันนี้สวย', ['this one is beautiful']],
  ['kǎo bpen fεεn pǒm', 'เขาเป็นแฟนผม', ['that is my partner', 'he is my boyfriend', 'she is my girlfriend']],
  ['dtua níi yài', 'ตัวนี้ใหญ่', ['this one is big', 'this animal is big']],
  ['pîi chûai nɔ́ɔng', 'พี่ช่วยน้อง', ['the older one helps the younger']],
  ['kǎo chà-làat mâak', 'เขาฉลาดมาก', ['he is very clever', 'she is very smart']],
  ['nɔ́ɔng kráp/ká', 'น้องครับ/คะ', ['excuse me, to a waiter', 'excuse me'], 'Calling out, a woman ends with ká.'],
  ['pîi kráp/ká', 'พี่ครับ/คะ', ['excuse me, to someone a bit older', 'excuse me']],
  ['bpâa kráp/ká, an níi tâo-rài', 'ป้าครับ/คะ อันนี้เท่าไร', ['auntie, how much is this one', 'how much is this one, auntie']],
  ['lung kráp/ká, jɔ̀ɔt tîi nîi', 'ลุงครับ/คะ จอดที่นี่', ['uncle, stop here', 'stop here, uncle']],
  ['nǔu mâi kâo jai kâ', 'หนูไม่เข้าใจค่ะ', ['I do not understand, a young woman to an elder']],
])
