import { phrases } from '../build'

export default phrases(15, [
  ['tâa pǒm wâang pǒm jà maa', 'ถ้าผมว่างผมจะมา', ['if I am free I will come']],
  ['prɔ́ wâa fǒn dtòk', 'เพราะว่าฝนตก', ['because it is raining']],
  ['pǒm yàak bpai dtὲε mâi wâang', 'ผมอยากไปแต่ไม่ว่าง', ['I want to go but I am not free']],
  ['gin kâao lέ glàp bâan', 'กินข้าวและกลับบ้าน', ['eat and go home']],
  ['gɔ̂ dâi', 'ก็ได้', ['fine', 'alright', 'that works']],
  ['mâi bpai ləəi', 'ไม่ไปเลย', ['I am not going at all']],
  ['kít wâa dii', 'คิดว่าดี', ['I think it is good']],
  ['kon tîi maa', 'คนที่มา', ['the person who came']],
  ['mέε wâa pεεng pǒm gɔ̂ ao', 'แม้ว่าแพงผมก็เอา', ['even if it is expensive I will take it']],
  ['nɔ̂ɔk jàak níi', 'นอกจากนี้', ['besides this', 'apart from this']],
  ['pụ̂a rian tai', 'เพื่อเรียนไทย', ['in order to study Thai']],
  ['dooi rót fai', 'โดยรถไฟ', ['by train']],
  ['kụụ wâa yang-ngai', 'คือว่ายังไง', ['what does that mean', 'so what is it']],
  ['rà-wàang bâan gàp ngaan', 'ระหว่างบ้านกับงาน', ['between home and work']],
  ['dtaam tîi kun bɔ̀ɔk', 'ตามที่คุณบอก', ['as you said']],
  ['dâng nán pǒm glàp', 'ดังนั้นผมกลับ', ['so I went back']],
  ['tâa mâi maa gɔ̂ mâi bpen rai', 'ถ้าไม่มาก็ไม่เป็นไร', ['if you do not come it is fine']],
  ['prɔ́ nụ̀ai', 'เพราะเหนื่อย', ['because I am tired']],
  ['dtὲε gɔ̂ chɔ̂ɔp', 'แต่ก็ชอบ', ['but I still like it']],
  ['hàak mii wee-laa', 'หากมีเวลา', ['if there is time']],
  ['lέ ìik yàang', 'และอีกอย่าง', ['and another thing']],
  ['gɔ̂ ləəi bpai', 'ก็เลยไป', ['so I just went']],
  ['wâa jà maa', 'ว่าจะมา', ['said they would come']],
  ['sụ̂ng yùu tîi nîi', 'ซึ่งอยู่ที่นี่', ['which is here']],
  ['táng sɔ̌ɔng kon', 'ทั้งสองคน', ['both people', 'both of them']],
  ['nụ̂ang jàak ngaan', 'เนื่องจากงาน', ['due to work']],
  ['tîi jà tam', 'ที่จะทำ', ['that I will do', 'to do']],
  ['jàak tîi pǒm rúu', 'จากที่ผมรู้', ['from what I know']],
  ['pɔɔ tîi jà gin', 'พอที่จะกิน', ['enough to eat']],
  ['rụ̌ụ wâa mâi maa', 'หรือว่าไม่มา', ['or perhaps not coming']],
])
