import { phrases } from '../build'

export default phrases(17, [
  ['gin ná', 'กินนะ', ['eat, will you', 'do eat']],
  ['bpai sì', 'ไปสิ', ['just go', 'go on']],
  ['jing rə̌ə', 'จริงเหรอ', ['really?', 'is that true']],
  ['mâi châi rɔ̀k', 'ไม่ใช่หรอก', ['it is not, you know', 'not at all']],
  ['dii ná kun', 'ดีนะคุณ', ['that is good of you']],
  ['ao sì ao sì', 'เอาสิเอาสิ', ['go on, take it']],
  ['yàa bpai wá', 'อย่าไปวะ', ['do not go (rough)']],
  ['maa já', 'มาจ๊ะ', ['come here (warm)']],
  ['sà-baai dii jâa', 'สบายดีจ้า', ['hello, I am fine (warm)']],
  ['kɔ̀ɔp kun ná', 'ขอบคุณนะ', ['thank you, you know']],
  ['kɔ̌ɔ tôot ná', 'ขอโทษนะ', ['sorry, okay?']],
  ['bpai gan ná', 'ไปกันนะ', ['let us go, yeah']],
  ['mâi ao rɔ̀k', 'ไม่เอาหรอก', ['I do not want it, no']],
  ['chɔ̂ɔp sì', 'ชอบสิ', ['of course I like it']],
  ['rúu sì', 'รู้สิ', ['I know, of course']],
  ['mâi maa rɔ̀k', 'ไม่มาหรอก', ['they are not coming', 'they will not come']],
  ['nîi rə̌ə', 'นี่เหรอ', ['this one?', 'this, really?']],
  ['təə lâ', 'เธอล่ะ', ['and you', 'what about you']],
  ['pǒm ná', 'ผมนะ', ['me, you know', 'I will']],
  ['kun sì', 'คุณสิ', ['you should', 'you then']],
  ['dâi ná', 'ได้นะ', ['you can, okay?']],
  ['mâi dâi rɔ̀k', 'ไม่ได้หรอก', ['you cannot, no']],
  ['yin-dii ná', 'ยินดีนะ', ['happy to, you know']],
  ['chôok dii ná', 'โชคดีนะ', ['good luck, yeah']],
  ['laa gɔ̀ɔn ná', 'ลาก่อนนะ', ['goodbye then']],
  ['fang ná', 'ฟังนะ', ['listen, okay?']],
  ['duu sì', 'ดูสิ', ['look then', 'just look']],
  ['lɔɔng sì', 'ลองสิ', ['just try it']],
  ['rɔɔ ná', 'รอนะ', ['wait, okay?']],
  ['maa sì', 'มาสิ', ['come on then']],
  ['jing jing ná', 'จริงๆนะ', ['really, I mean it']],
  ['mâi wâang rɔ̀k', 'ไม่ว่างหรอก', ['I am not free, no']],
  ['ao ná', 'เอานะ', ['take it, okay?']],
  ['bpai ləəi ná', 'ไปเลยนะ', ['just go, you know']],
  ['sèt ná', 'เสร็จนะ', ['done, okay?']],
  ['tǔng lέεo rə̌ə', 'ถึงแล้วเหรอ', ['already there, really?']],
])
