import { phrases } from '../build'

export default phrases(2, [
  ['pǒm gin kâao', 'ผมกินข้าว', ['I eat', 'I am eating', 'I eat rice', 'I am having a meal'], 'gin kâao = eat rice = eat, full stop.'],
  ['pǒm chɔ̂ɔp gaa-fεε', 'ผมชอบกาแฟ', ['I like coffee']],
  ['pǒm mâi chɔ̂ɔp bia', 'ผมไม่ชอบเบียร์', ['I do not like beer']],
  ['kun mii rót mái', 'คุณมีรถไหม', ['do you have a car']],
  ['pǒm mii pụ̂an kon tai', 'ผมมีเพื่อนคนไทย', ['I have a Thai friend', 'I have Thai friends']],
  ['rao bpai gin kâao gan', 'เราไปกินข้าวกัน', ['let us go eat together', 'we go eat together', 'let us go and eat', 'shall we go eat']],
  ['pǒm rian paa-sǎa tai', 'ผมเรียนภาษาไทย', ['I study Thai', 'I am learning Thai', 'I learn Thai']],
  ['kǎo tam-ngaan tîi grung-têep', 'เขาทำงานที่กรุงเทพ', ['he works in Bangkok', 'she works in Bangkok', 'they work in Bangkok']],
  ['pǒm yùu tîi grung-têep', 'ผมอยู่ที่กรุงเทพ', ['I live in Bangkok', 'I am in Bangkok', 'I stay in Bangkok']],
  ['kun kâo jai mái', 'คุณเข้าใจไหม', ['do you understand']],
  ['pǒm hěn kun', 'ผมเห็นคุณ', ['I see you', 'I saw you']],
  ['kǎo mâi maa', 'เขาไม่มา', ['he is not coming', 'she is not coming', 'he did not come', 'they are not coming']],
  ['pǒm glàp bâan', 'ผมกลับบ้าน', ['I go home', 'I am going home', 'I went home', 'I return home']],
  ['pǒm dtụ̀ụn cháa', 'ผมตื่นช้า', ['I woke up late', 'I wake up late', 'I got up late']],
  ['kǎo nɔɔn lέεo', 'เขานอนแล้ว', ['he is already asleep', 'she has gone to bed', 'he already went to sleep', 'they are asleep already']],
  ['kun àan nǎng-sụ̌ụ mái', 'คุณอ่านหนังสือไหม', ['do you read books', 'do you read']],
  ['pǒm fang mâi kâo jai', 'ผมฟังไม่เข้าใจ', ['I listen but do not understand', 'I hear it but I do not understand', 'I do not understand what I hear']],
  ['pǒm hǎa hɔ̂ng náam', 'ผมหาห้องน้ำ', ['I am looking for the toilet', 'I am looking for the bathroom']],
  ['kun pûut tai gèng', 'คุณพูดไทยเก่ง', ['you speak Thai well', 'your Thai is good', 'you are good at Thai'], 'What every Thai says after your first sà-wàt-dii.'],
  ['rian gèng', 'เรียนเก่ง', ['good at studying', 'a good learner', 'good student', 'studies well'], 'The name of this app.'],
  ['yin-dii tîi dâi rúu-jàk kráp/kâ', 'ยินดีที่ได้รู้จักครับ/ค่ะ', ['nice to meet you', 'pleased to meet you']],
  ['nân kɔ̌ɔng pǒm', 'นั่นของผม', ['that is mine', 'that is my thing', 'that belongs to me']],
  ['pǒm rák kun', 'ผมรักคุณ', ['I love you']],
  ['kǎo bɔ̀ɔk pǒm', 'เขาบอกผม', ['he told me', 'she told me', 'they told me', 'he tells me']],
  ['bpə̀ət bpìt', 'เปิดปิด', ['open and close', 'on and off', 'open close']],
  ['sèt lέεo', 'เสร็จแล้ว', ['done', 'finished', 'it is done', 'all done', 'ready']],
])
