import { phrases } from '../build'

export default phrases(21, [
  ['pǒm pûut tai dâi lέεo', 'ผมพูดไทยได้แล้ว', ['I can speak Thai now']],
  ['prà-yòok níi kâo jai ngâai', 'ประโยคนี้เข้าใจง่าย', ['this sentence is easy to understand']],
  ['kwaam mǎai kụụ à-rai', 'ความหมายคืออะไร', ['what does it mean']],
  ['sǎm-nuan níi sǔai', 'สำนวนนี้สวย', ['this saying is beautiful']],
  ['pûut cháa ìik nɔ̀i', 'พูดช้าอีกหน่อย', ['speak a bit more slowly']],
  ['sǔan yài kâo jai', 'ส่วนใหญ่เข้าใจ', ['mostly I understand']],
  ['bpai dtàang prà-têet', 'ไปต่างประเทศ', ['go abroad']],
  ['rian paa-sǎa glaang', 'เรียนภาษากลาง', ['study central Thai']],
  ['kam níi yâak', 'คำนี้ยาก', ['this word is hard']],
  ['bɔ̀ɔk bpen prà-yòok', 'บอกเป็นประโยค', ['say it as a sentence']],
  ['pûut reo pǒm mâi than', 'พูดเร็วผมไม่ทัน', ['you speak fast I cannot keep up']],
  ['dâi yin kam níi', 'ได้ยินคำนี้', ['I have heard this word']],
  ['kít bpen paa-sǎa tai', 'คิดเป็นภาษาไทย', ['think in Thai']],
  ['mâi dtɔ̂ng pûut pεεng', 'ไม่ต้องพูดแพง', ['no need for fancy talk']],
  ['sǎm-nuan tai mâak', 'สำนวนไทยมาก', ['very Thai phrasing']],
  ['pûut dâi dtὲε yang nít-nɔ̀i', 'พูดได้แต่ยังนิดหน่อย', ['I can speak but only a little']],
  ['prà-yòok sɔ̌ɔng prà-yòok', 'ประโยคสองประโยค', ['two sentences']],
  ['kâo jai táng prà-yòok', 'เข้าใจทั้งประโยค', ['I understand the whole sentence']],
  ['sǔan nɔ́ɔi tîi pìt', 'ส่วนน้อยที่ผิด', ['only a little is wrong']],
  ['wan níi pûut dâi mâak gwàa', 'วันนี้พูดได้มากกว่า', ['today I can say more']],
  ['gèng kụ̂n lέεo', 'เก่งขึ้นแล้ว', ['better already', 'improved']],
])
