import { phrases } from '../build'

export default phrases(1, [
  ['sà-wàt-dii kráp/kâ', 'สวัสดีครับ/ค่ะ', ['hello', 'hi', 'good day', 'goodbye'], 'Men say kráp, women say kâ.'],
  ['kɔ̀ɔp kun mâak', 'ขอบคุณมาก', ['thank you very much', 'thanks a lot', 'thank you so much']],
  ['kɔ̀ɔp kun kráp/kâ', 'ขอบคุณครับ/ค่ะ', ['thank you', 'thanks']],
  ['kɔ̌ɔ tôot kráp/kâ', 'ขอโทษครับ/ค่ะ', ['sorry', 'excuse me', 'I am sorry']],
  ['mâi bpen rai', 'ไม่เป็นไร', ['never mind', 'it is okay', 'no problem', 'you are welcome', 'do not worry about it', 'it does not matter'], 'The most Thai sentence there is. Answer to thanks and to apologies alike.'],
  ['sà-baai dii mái', 'สบายดีไหม', ['how are you', 'are you well', 'how are you doing'], 'Literally "well, yes?"'],
  ['sà-baai dii kráp/kâ', 'สบายดีครับ/ค่ะ', ['I am fine', 'fine thanks', 'I am well', 'I am good']],
  ['pǒm mâi kâo jai', 'ผมไม่เข้าใจ', ['I do not understand'], 'chǎn mâi kâo jai for a woman.'],
  ['kâo jai lέεo', 'เข้าใจแล้ว', ['I understand now', 'got it', 'I understand', 'understood']],
  ['pûut cháa cháa nɔ̀i', 'พูดช้าๆหน่อย', ['speak slowly please', 'please speak slowly', 'slower please', 'can you speak slowly']],
  ['pûut ìik tii dâi mái', 'พูดอีกทีได้ไหม', ['can you say it again', 'say it again please', 'could you repeat that', 'one more time please']],
  ['pǒm pûut tai dâi nít-nɔ̀i', 'ผมพูดไทยได้นิดหน่อย', ['I speak a little Thai', 'I can speak a little Thai', 'I speak Thai a little']],
  ['kun pûut paa-sǎa ang-grìt dâi mái', 'คุณพูดภาษาอังกฤษได้ไหม', ['can you speak English', 'do you speak English']],
  ['mâi rúu kráp/kâ', 'ไม่รู้ครับ/ค่ะ', ['I do not know', 'no idea']],
  ['dâi kráp/kâ', 'ได้ครับ/ค่ะ', ['yes', 'sure', 'ok', 'can do', 'yes I can', 'that works']],
  ['mâi dâi kráp/kâ', 'ไม่ได้ครับ/ค่ะ', ['no', 'I cannot', 'that is not possible', 'not possible']],
  ['chûai dûai', 'ช่วยด้วย', ['help', 'help me', 'help!'], 'The shout, not the polite request.'],
  ['kɔ̌ɔ náam nɔ̀i', 'ขอน้ำหน่อย', ['can I have some water', 'water please', 'may I have water', 'some water please']],
  ['mâi ao', 'ไม่เอา', ['I do not want it', 'no thanks', 'I do not want', 'no I do not want it'], 'Blunt but normal. Add kráp/kâ to soften.'],
  ['ao kráp/kâ', 'เอาครับ/ค่ะ', ['yes please', 'I will take it', 'I want it', 'yes I want it']],
  ['bpai gɔ̀ɔn ná', 'ไปก่อนนะ', ['I am off', 'I will go first', 'see you', 'bye for now', 'I am going now'], 'The everyday goodbye.'],
  ['chôok dii kráp/kâ', 'โชคดีครับ/ค่ะ', ['good luck', 'take care', 'goodbye and good luck']],
  ['mâi mii', 'ไม่มี', ['there is none', 'do not have', 'I do not have', 'there is not', 'none']],
  ['mii mái', 'มีไหม', ['do you have', 'is there', 'do you have any', 'are there']],
])
