import { phrases } from '../build'

export default phrases(12, [
  ['kun sà-baai dii mái', 'คุณสบายดีไหม', ['how are you', 'are you well']],
  ['pǒm mâi sà-baai', 'ผมไม่สบาย', ['I am unwell', 'I am not well']],
  ['pǒm jèp', 'ผมเจ็บ', ['I am in pain', 'it hurts']],
  ['bpùat hǔa mâak', 'ปวดหัวมาก', ['I have a bad headache']],
  ['dtɔ̂ng bpai hǎa mɔ̌ɔ', 'ต้องไปหาหมอ', ['I have to see a doctor']],
  ['pǒm nʉ̀ai', 'ผมเหนื่อย', ['I am tired']],
  ['pǒm bʉ̀a', 'ผมเบื่อ', ['I am bored']],
  ['kǎo gròot', 'เขาโกรธ', ['he is angry', 'she is angry']],
  ['pǒm dii jai', 'ผมดีใจ', ['I am glad', 'I am happy']],
  ['dtà-lòk mâak', 'ตลกมาก', ['so funny[, 555]', 'very funny', 'really funny', 'hilarious']],
  ['pǒm sǐa jai', 'ผมเสียใจ', ['I am sad', 'I am sorry']],
  ['mii kâi', 'มีไข้', ['I have a fever', 'have a fever']],
  ['pέε à-rai', 'แพ้อะไร', ['what are you allergic to']],
  ['ao yaa nɔ̀i', 'เอายาหน่อย', ['some medicine please']],
  ['bpùat hǔa táng wan', 'ปวดหัวทั้งวัน', ['my head hurt all day']],
  ['bpùat fan', 'ปวดฟัน', ['toothache', 'my tooth hurts']],
  ['rao bpai roong-pá-yaa-baan', 'เราไปโรงพยาบาล', ['we are going to the hospital']],
  ['pǒm rúu-sʉ̀k dii kʉ̂n', 'ผมรู้สึกดีขึ้น', ['I feel better']],
  ['yang bpùai yùu', 'ยังป่วยอยู่', ['still sick', 'still ill']],
  ['pǒm pέε tùa', 'ผมแพ้ถั่ว', ['I am allergic to peanuts', 'I am allergic to nuts']],
  ['nûat tai', 'นวดไทย', ['Thai massage']],
  ['nûat táo', 'นวดเท้า', ['foot massage']],
  ['bao bao nɔ̀i', 'เบาๆหน่อย', ['gently, please', 'a bit softer']],
  ['rεεng kʉ̂n nɔ̀i', 'แรงขึ้นหน่อย', ['a bit harder', 'a little stronger']],
])
