import { phrases } from '../build'

export default phrases(19, [
  ['pǒm kít wâa dii', 'ผมคิดว่าดี', ['I think it is good']],
  ['pǒm rúu-sʉ̀k wâa pìt', 'ผมรู้สึกว่าผิด', ['I feel that it is wrong']],
  ['pǒm hěn dûai', 'ผมเห็นด้วย', ['I agree']],
  ['pǒm mâi hěn dûai', 'ผมไม่เห็นด้วย', ['I disagree']],
  ['pǒm chʉ̂a kun', 'ผมเชื่อคุณ', ['I believe you']],
  ['mâi chʉ̂a rɔ̀k', 'ไม่เชื่อหรอก', ['I do not believe that']],
  ['sǒng-sǎi wâa jing rʉ̌ʉ bplào', 'สงสัยว่าจริงหรือเปล่า', ['I wonder if it is true', 'I wonder whether it is true']],
  ['kun nε̂ε jai mái', 'คุณแน่ใจไหม', ['are you sure']],
  ['mâi nε̂ε jai', 'ไม่แน่ใจ', ['I am not sure']],
  ['yɔɔm-ráp wâa pìt', 'ยอมรับว่าผิด', ['I admit I was wrong']],
  ['lâo rʉ̂ang nɔ̀i', 'เล่าเรื่องหน่อย', ['tell the story', 'tell me about it']],
  ['rʉ̂ang tîi kəəi lâo', 'เรื่องที่เคยเล่า', ['the story I told before', 'the story from before']],
  ['dtɔɔn rε̂εk pǒm ngong', 'ตอนแรกผมงง', ['at first I was confused']],
  ['jàak nán kâo jai', 'จากนั้นเข้าใจ', ['after that I understood']],
  ['sùt táai gɔ̂ dii', 'สุดท้ายก็ดี', ['in the end it was fine']],
  ['pǒm kít tǔng bâan', 'ผมคิดถึงบ้าน', ['I miss home']],
  ['nîi jing mái', 'นี่จริงไหม', ['is this true']],
  ['kwaam hěn pǒm', 'ความเห็นผม', ['my opinion']],
  ['sà-rúp lέεo', 'สรุปแล้ว', ['in conclusion', 'to sum up']],
  ['dtɔ̀ɔ bpai yang-ngai', 'ต่อไปยังไง', ['what next', 'what now']],
  ['lâo mâi sèt', 'เล่าไม่เสร็จ', ['I have not finished the story']],
  ['kít wâa jà maa', 'คิดว่าจะมา', ['I thought they would come']],
  ['hěn dûai mâak', 'เห็นด้วยมาก', ['I agree a lot']],
  ['mâi chʉ̂a dtὲε fang', 'ไม่เชื่อแต่ฟัง', ['I do not believe it but I listen']],
  ['rʉ̂ang níi yaao', 'เรื่องนี้ยาว', ['this is a long story']],
  ['kwaam kít dii', 'ความคิดดี', ['a good idea']],
])
