import { phrases } from '../build'

export default phrases(4, [
  ['kɔ̌ɔ mee-nuu nɔ̀i', 'ขอเมนูหน่อย', ['can I have the menu please', 'menu please', 'may I see the menu']],
  ['ao kâao pàt gài', 'เอาข้าวผัดไก่', ['I will have chicken fried rice', 'chicken fried rice please', 'I want chicken fried rice']],
  ['ao pàt tai sɔ̌ɔng jaan', 'เอาผัดไทยสองจาน', ['two pad thai please', 'I will have two plates of pad thai', 'two plates of pad thai']],
  ['kɔ̌ɔ náam bplào nʉ̀ng kùat', 'ขอน้ำเปล่าหนึ่งขวด', ['one bottle of water please', 'a bottle of water please', 'can I have a bottle of water']],
  ['kɔ̌ɔ gaa-fεε yen nʉ̀ng gε̂εo', 'ขอกาแฟเย็นหนึ่งแก้ว', ['one iced coffee please', 'an iced coffee please', 'can I have one iced coffee']],
  ['mâi pèt', 'ไม่เผ็ด', ['not spicy', 'no spice', 'make it not spicy']],
  ['pèt nít-nɔ̀i', 'เผ็ดนิดหน่อย', ['a little spicy', 'slightly spicy', 'a bit spicy']],
  ['pèt mâak', 'เผ็ดมาก', ['very spicy', 'really spicy']],
  ['mâi sài prík', 'ไม่ใส่พริก', ['no chilli', 'without chilli', 'do not add chilli', 'no chili']],
  ['mâi sài náam dtaan', 'ไม่ใส่น้ำตาล', ['no sugar', 'without sugar', 'do not add sugar']],
  ['mâi sài náam kε̌ng', 'ไม่ใส่น้ำแข็ง', ['no ice', 'without ice']],
  ['sài prík nít-nɔ̀i', 'ใส่พริกนิดหน่อย', ['a little chilli', 'just a little chilli', 'add a bit of chilli']],
  ['à-rɔ̀i mâak', 'อร่อยมาก', ['very delicious', 'so tasty', 'really delicious', 'very tasty']],
  ['à-rɔ̀i mái', 'อร่อยไหม', ['is it delicious', 'is it good', 'is it tasty', 'do you like the food']],
  ['gèp dtang dûai', 'เก็บตังค์ด้วย', ['the bill please', 'can I pay please', 'check please']],
  ['chék bin kráp/kâ', 'เช็คบิลครับ/ค่ะ', ['the bill please', 'check please', 'bill please']],
  ['tâo-rài kráp/kâ', 'เท่าไรครับ/ค่ะ', ['how much is it', 'how much', 'how much do I owe']],
  ['pǒm hǐu', 'ผมหิว', ['I am hungry']],
  ['pǒm ìm lέεo', 'ผมอิ่มแล้ว', ['I am full', 'I am full already', 'I have had enough']],
  ['gin tîi nîi', 'กินที่นี่', ['eat here', 'for here', 'I will eat here']],
  ['mii à-rai à-rɔ̀i bâang', 'มีอะไรอร่อยบ้าง', ['what is good here', 'what do you recommend', 'what tasty things do you have']],
  ['pǒm gin pèt mâi dâi', 'ผมกินเผ็ดไม่ได้', ['I cannot eat spicy food', 'I cannot eat spicy']],
  ['pǒm mâi gin nʉ́a', 'ผมไม่กินเนื้อ', ['I do not eat beef', 'I do not eat meat']],
  ['pǒm gin pàk', 'ผมกินผัก', ['I eat vegetables', 'I eat veggies']],
  ['kɔ̌ɔ ìik nɔ̀i', 'ขออีกหน่อย', ['a little more please', 'can I have some more', 'more please']],
  ['kɔ̌ɔ náam kε̌ng nɔ̀i', 'ขอน้ำแข็งหน่อย', ['some ice please', 'can I have some ice']],
  ['wǎan gəən bpai', 'หวานเกินไป', ['too sweet']],
  ['gin kâao rʉ̌ʉ yang', 'กินข้าวหรือยัง', ['have you eaten yet', 'have you eaten', 'did you eat yet'], 'The second Thai greeting. Not really about food.'],
  ['gin lέεo', 'กินแล้ว', ['I have eaten', 'already ate', 'eaten already']],
  ['yang mâi gin', 'ยังไม่กิน', ['not yet eaten', 'I have not eaten yet', 'not yet']],
])
