import { phrases } from '../build'

export default phrases(5, [
  ['gìi moong lέεo', 'กี่โมงแล้ว', ['what time is it', 'what time is it now']],
  ['bàai sɔ̌ɔng moong', 'บ่ายสองโมง', ['two in the afternoon', '2 p.m.', 'two p.m.']],
  ['sɔ̌ɔng tûm', 'สองทุ่ม', ['eight in the evening', '8 p.m.', 'eight p.m.']],
  ['dtii sɔ̌ɔng', 'ตีสอง', ['two in the morning', '2 a.m.', 'two a.m.']],
  ['nîi gìi bàat', 'นี่กี่บาท', ['how many baht is this', 'how much is this in baht']],
  ['rɔ́ɔi bàat', 'ร้อยบาท', ['one hundred baht', 'a hundred baht', '100 baht']],
  ['sɔ̌ɔng rɔ́ɔi bàat', 'สองร้อยบาท', ['two hundred baht', '200 baht']],
  ['nʉ̀ng pan bàat', 'หนึ่งพันบาท', ['one thousand baht', 'a thousand baht', '1000 baht']],
  ['mii ngən tɔɔn mái', 'มีเงินทอนไหม', ['do you have change', 'do you have change for this']],
  ['wan níi wan à-rai', 'วันนี้วันอะไร', ['what day is it today', 'what day is today']],
  ['mʉ̂a-waan pǒm yùu bâan', 'เมื่อวานผมอยู่บ้าน', ['yesterday I was at home', 'I was home yesterday']],
  ['prûng-níi pǒm wâang', 'พรุ่งนี้ผมว่าง', ['tomorrow I am free', 'I am free tomorrow']],
  ['nʉ̀ng chûa-moong', 'หนึ่งชั่วโมง', ['one hour', 'an hour']],
  ['sìp naa-tii', 'สิบนาที', ['ten minutes']],
  ['jà bpai gìi moong', 'จะไปกี่โมง', ['what time will you go', 'what time are we going']],
  ['hòk moong cháao', 'หกโมงเช้า', ['six in the morning', '6 a.m.', 'six a.m.']],
  ['jèt moong cháao', 'เจ็ดโมงเช้า', ['seven in the morning', '7 a.m.', 'seven a.m.']],
  ['bpὲεt moong krʉ̂ng', 'แปดโมงครึ่ง', ['half past eight', '8:30 a.m.', 'eight thirty']],
  ['sìp moong', 'สิบโมง', ['ten in the morning', '10 a.m.', 'ten a.m.']],
  ['bàai moong', 'บ่ายโมง', ['one in the afternoon', '1 p.m.', 'one p.m.'], 'Not bàai nʉ̀ng moong. One in the afternoon is just bàai moong.'],
  ['bàai sǎam moong', 'บ่ายสามโมง', ['three in the afternoon', '3 p.m.', 'three p.m.']],
  ['sìi moong yen', 'สี่โมงเย็น', ['four in the afternoon', '4 p.m.', 'four p.m.']],
  ['hâa moong yen', 'ห้าโมงเย็น', ['five in the evening', '5 p.m.', 'five p.m.']],
  ['nʉ̀ng tûm', 'หนึ่งทุ่ม', ['seven in the evening', '7 p.m.', 'seven p.m.'], 'The evening counts again from one. nʉ̀ng tûm is 7 p.m., sɔ̌ɔng tûm is 8.'],
  ['dtii nʉ̀ng', 'ตีหนึ่ง', ['one in the morning', '1 a.m.', 'one a.m.']],
])
