import { phrases } from '../build'

export default phrases(3, [
  ['kun bpai tîi-nǎi', 'คุณไปที่ไหน', ['where are you going', 'where do you go']],
  ['bpai nǎi maa', 'ไปไหนมา', ['where have you been', 'where did you go'], 'The everyday Thai greeting. The answer can be vague.'],
  ['kun maa jàak tîi-nǎi', 'คุณมาจากที่ไหน', ['where are you from', 'where do you come from']],
  ['kun maa jàak bprà-têet à-rai', 'คุณมาจากประเทศอะไร', ['what country are you from', 'which country are you from']],
  ['pǒm maa jàak sà-bpeen', 'ผมมาจากสเปน', ['I am from Spain', 'I come from Spain']],
  ['kun tam à-rai', 'คุณทำอะไร', ['what are you doing', 'what do you do']],
  ['kun tam-ngaan à-rai', 'คุณทำงานอะไร', ['what is your job', 'what do you do for work', 'what work do you do']],
  ['kun yùu tîi-nǎi', 'คุณอยู่ที่ไหน', ['where do you live', 'where are you']],
  ['kun chʉ̂ʉ à-rai', 'คุณชื่ออะไร', ['what is your name', 'what are you called']],
  ['nîi à-rai', 'นี่อะไร', ['what is this']],
  ['hɔ̂ng náam yùu tîi-nǎi', 'ห้องน้ำอยู่ที่ไหน', ['where is the toilet', 'where is the bathroom']],
  ['roong-rεεm yùu tîi-nǎi', 'โรงแรมอยู่ที่ไหน', ['where is the hotel']],
  ['kun maa tʉ̌ng mʉ̂a-rài', 'คุณมาถึงเมื่อไร', ['when did you arrive', 'when did you get here']],
  ['tam-mai kun rian paa-sǎa tai', 'ทำไมคุณเรียนภาษาไทย', ['why do you study Thai', 'why are you learning Thai']],
  ['nîi krai', 'นี่ใคร', ['who is this']],
  ['krai maa', 'ใครมา', ['who is coming', 'who came']],
  ['bpai yang-ngai', 'ไปยังไง', ['how do I get there', 'how do you go', 'how to get there']],
  ['pûut yang-ngai', 'พูดยังไง', ['how do you say it', 'how do you say', 'how is it said']],
  ['nîi tâo-rài', 'นี่เท่าไร', ['how much is this', 'how much is it']],
  ['kun aa-yú tâo-rài', 'คุณอายุเท่าไร', ['how old are you', 'what is your age']],
  ['mii gìi kon', 'มีกี่คน', ['how many people are there', 'how many people']],
  ['gìi bàat', 'กี่บาท', ['how many baht', 'how much (in baht)']],
  ['kun chɔ̂ɔp mái', 'คุณชอบไหม', ['do you like it', 'do you like']],
  ['kun chɔ̂ɔp rʉ̌ʉ bplào', 'คุณชอบหรือเปล่า', ['do you like it or not', 'do you like it']],
  ['kun bpen kon tai châi mái', 'คุณเป็นคนไทยใช่ไหม', ['you are Thai right', 'you are Thai aren’t you', 'are you Thai']],
  ['kun lâ', 'คุณล่ะ', ['and you', 'what about you', 'how about you']],
  ['mii à-rai bâang', 'มีอะไรบ้าง', ['what do you have', 'what is there', 'what things are there', 'what have you got']],
  ['an nǎi', 'อันไหน', ['which one']],
  ['an níi', 'อันนี้', ['this one']],
  ['an níi tâo-rài', 'อันนี้เท่าไร', ['how much is this one']],
  ['bpai rʉ̌ʉ', 'ไปหรือ', ['oh you are going?', 'are you going?', 'going, are you?']],
  ['kun rúu mái', 'คุณรู้ไหม', ['do you know']],
  ['mâi rúu wâa krai', 'ไม่รู้ว่าใคร', ['I do not know who', 'do not know who it is']],
])
