import { words } from '../build'

export default words(7, [
  ['yang', 'ยัง', ['still', 'not yet', 'yet'], 'adv', ['aspect']],
  ['gam-lang', 'กำลัง', ['in the middle of', 'currently', 'in the process of'], 'adv', ['aspect']],
  ['jà', 'จะ', ['will', 'going to', 'about to'], 'adv', ['aspect']],
  ['kəəi', 'เคย', ['ever', 'used to'], 'adv', ['aspect']],
  ['gɔ̀ɔn', 'ก่อน', ['before', 'first'], 'adv', ['aspect']],
  ['dtɔɔn', 'ตอน', ['when', 'at the time', 'period'], 'n', ['time']],
  ['dtɔɔn nîi', 'ตอนนี้', ['now', 'at this moment'], 'adv', ['time']],
  ['dtɔɔn nán', 'ตอนนั้น', ['then', 'at that time'], 'adv', ['time']],
  ['mụ̂a', 'เมื่อ', ['when', 'when (in the past)'], 'conj', ['time']],
  ['mụ̂a gɔ̀ɔn', 'เมื่อก่อน', ['before', 'in the past', 'formerly'], 'adv', ['time']],
  ['jàak nán', 'จากนั้น', ['after that', 'then'], 'adv', ['time']],
  ['sùt táai', 'สุดท้าย', ['finally', 'in the end', 'last'], 'adv', ['time']],
  ['náan', 'นาน', ['a long time', 'long'], 'adv', ['time']],
  ['bɔ̀i', 'บ่อย', ['often', 'frequently'], 'adv', ['time']],
  ['tûk wan', 'ทุกวัน', ['every day', 'everyday'], 'adv', ['time']],
  ['tûk dụụan', 'ทุกเดือน', ['every month'], 'adv', ['time']],
  ['tûk bpii', 'ทุกปี', ['every year'], 'adv', ['time']],
  ['wan lá', 'วันละ', ['per day', 'a day'], 'adv', ['time']],
  ['yang mâi', 'ยังไม่', ['not yet'], 'adv', ['aspect']],
  ['bpen yùu', 'เป็นอยู่', ['still is', 'remains'], 'expr', ['aspect']],
  ['pə̂ng', 'เพิ่ง', ['just', 'just now', 'only just'], 'adv', ['aspect']],
  ['kəəi lέεo', 'เคยแล้ว', ['have already', 'have ever'], 'expr', ['aspect']],
  ['tûk kráng', 'ทุกครั้ง', ['every time'], 'adv', ['time']],
  ['dtɔɔn rɔ̂ɔk', 'ตอนแรก', ['at first', 'in the beginning'], 'adv', ['time']],
  ['lǎng jàak', 'หลังจาก', ['after'], 'prep', ['time']],
  ['gɔ̀ɔn nâa', 'ก่อนหน้า', ['previously', 'beforehand'], 'adv', ['time']],
  ['diao nîi', 'เดี๋ยวนี้', ['right now', 'just now'], 'adv', ['time']],
  ['diao', 'เดี๋ยว', ['in a moment', 'wait', 'soon'], 'adv', ['time']],
  ['nâa nîi', 'หน้านี้', ['this time', 'this page'], 'n', ['time']],
  ['kráng nâa', 'ครั้งหน้า', ['next time'], 'adv', ['time']],
  ['kráng gɔ̀ɔn', 'ครั้งก่อน', ['last time', 'the previous time'], 'adv', ['time']],
])
