import { words } from '../build'

export default words(4, [
  // dishes
  ['kâao pàt', 'ข้าวผัด', ['fried rice'], 'n', ['dish']],
  ['pàt tai', 'ผัดไทย', ['pad thai', 'fried noodles (pad thai)'], 'n', ['dish']],
  ['dtôm yam', 'ต้มยำ', ['tom yum', 'tom yum soup', 'spicy sour soup'], 'n', ['dish']],
  ['dtôm yam gûng', 'ต้มยำกุ้ง', ['tom yum with shrimp', 'shrimp tom yum', 'tom yum goong'], 'n', ['dish']],
  ['sôm dtam', 'ส้มตำ', ['papaya salad', 'som tam', 'spicy papaya salad'], 'n', ['dish']],
  ['gεεng', 'แกง', ['curry', 'soup (curry)'], 'n', ['dish']],
  ['gεεng kǐao wǎan', 'แกงเขียวหวาน', ['green curry'], 'n', ['dish'], 'Literally "sweet green curry".'],
  ['kâao nǐao', 'ข้าวเหนียว', ['sticky rice'], 'n', ['dish']],
  ['kâao nǐao má-mûang', 'ข้าวเหนียวมะม่วง', ['mango sticky rice', 'mango with sticky rice'], 'n', ['dish']],
  ['gǔai-dtǐao', 'ก๋วยเตี๋ยว', ['noodles', 'noodle soup', 'rice noodles'], 'n', ['dish']],
  ['kâao dtôm', 'ข้าวต้ม', ['rice porridge', 'boiled rice soup', 'congee'], 'n', ['dish']],
  ['kài jiao', 'ไข่เจียว', ['omelette', 'Thai omelette', 'omelet'], 'n', ['dish']],
  ['kài dao', 'ไข่ดาว', ['fried egg', 'sunny side up egg'], 'n', ['dish'], 'Literally "star egg".'],
  ['gài tɔ̂ɔt', 'ไก่ทอด', ['fried chicken'], 'n', ['dish']],
  ['mǔu bpîng', 'หมูปิ้ง', ['grilled pork', 'grilled pork skewers', 'pork skewers'], 'n', ['dish']],
  // ingredients
  ['gûng', 'กุ้ง', ['shrimp', 'prawn', 'prawns'], 'n', ['food']],
  ['bplaa', 'ปลา', ['fish'], 'n', ['food']],
  ['mǔu', 'หมู', ['pork', 'pig'], 'n', ['food']],
  ['nụ́a', 'เนื้อ', ['beef', 'meat'], 'n', ['food']],
  ['pàk', 'ผัก', ['vegetable', 'vegetables', 'greens'], 'n', ['food']],
  ['pǒn-lá-mái', 'ผลไม้', ['fruit'], 'n', ['food']],
  ['má-mûang', 'มะม่วง', ['mango'], 'n', ['food']],
  ['glûai', 'กล้วย', ['banana'], 'n', ['food']],
  ['sàp-bpà-rót', 'สับปะรด', ['pineapple'], 'n', ['food']],
  ['má-lá-gɔɔ', 'มะละกอ', ['papaya'], 'n', ['food']],
  ['má-práao', 'มะพร้าว', ['coconut'], 'n', ['food']],
  ['prík', 'พริก', ['chilli', 'chili', 'chili pepper'], 'n', ['food']],
  ['náam bplaa', 'น้ำปลา', ['fish sauce'], 'n', ['food']],
  ['náam dtaan', 'น้ำตาล', ['sugar'], 'n', ['food'], 'Literally "palm water".'],
  ['glua', 'เกลือ', ['salt'], 'n', ['food']],
  ['má-naao', 'มะนาว', ['lime', 'lemon'], 'n', ['food']],
  ['kà-nǒm', 'ขนม', ['snack', 'dessert', 'sweets', 'cake'], 'n', ['food']],
  ['kà-nǒm bpang', 'ขนมปัง', ['bread'], 'n', ['food']],
  // drinks
  ['náam bplào', 'น้ำเปล่า', ['plain water', 'drinking water', 'still water'], 'n', ['drink']],
  ['náam kε̌ng', 'น้ำแข็ง', ['ice'], 'n', ['drink']],
  ['chaa', 'ชา', ['tea'], 'n', ['drink']],
  ['chaa yen', 'ชาเย็น', ['Thai iced tea', 'iced tea'], 'n', ['drink']],
  ['náam sôm', 'น้ำส้ม', ['orange juice'], 'n', ['drink']],
  ['náam má-práao', 'น้ำมะพร้าว', ['coconut water', 'coconut juice'], 'n', ['drink']],
  ['nom', 'นม', ['milk'], 'n', ['drink']],
  ['gaa-fεε yen', 'กาแฟเย็น', ['iced coffee'], 'n', ['drink']],
  ['gaa-fεε rɔ́ɔn', 'กาแฟร้อน', ['hot coffee'], 'n', ['drink']],
  // tastes
  ['à-rɔ̀i', 'อร่อย', ['delicious', 'tasty', 'yummy'], 'adj', ['taste']],
  ['wǎan', 'หวาน', ['sweet'], 'adj', ['taste']],
  ['bprîao', 'เปรี้ยว', ['sour'], 'adj', ['taste']],
  ['kem', 'เค็ม', ['salty'], 'adj', ['taste']],
  ['kǒm', 'ขม', ['bitter'], 'adj', ['taste']],
  ['jùut', 'จืด', ['bland', 'tasteless', 'plain'], 'adj', ['taste']],
  ['hǐu', 'หิว', ['hungry'], 'adj', ['feeling']],
  ['ìm', 'อิ่ม', ['full', 'full (after eating)', 'I am full'], 'adj', ['feeling']],
  ['hǐu náam', 'หิวน้ำ', ['thirsty'], 'adj', ['feeling'], 'Literally "hungry for water".'],
  // ordering
  ['sàng', 'สั่ง', ['order', 'to order'], 'v', ['ordering']],
  ['tá-naa-kaan', 'ธนาคาร', ['bank'], 'n', ['money']],
  ['gèp dtang', 'เก็บตัง', ['the bill please', 'check please', 'collect the money', 'bill please'], 'expr', ['ordering'], 'Literally "collect money". Also chék bin.'],
  ['chék bin', 'เช็คบิล', ['the bill please', 'check bill', 'bill please'], 'expr', ['ordering'], 'From "check bill". Same as gèp dtang.'],
  ['mee-nuu', 'เมนู', ['menu'], 'n', ['ordering']],
  ['jaan#2', 'จาน', ['plate', 'dish (classifier)', 'a plate of'], 'clf', ['classifier'], 'Also the classifier: kâao pàt sɔ̌ɔng jaan = two plates of fried rice.'],
  ['gε̂εo', 'แก้ว', ['glass', 'cup', 'glass (classifier)'], 'n', ['classifier'], 'Also the classifier for drinks: náam nụ̀ng gε̂εo.'],
  ['kùat', 'ขวด', ['bottle', 'bottle (classifier)'], 'n', ['classifier']],
  ['tûai', 'ถ้วย', ['cup', 'bowl (small)', 'cup (classifier)'], 'n', ['classifier']],
  ['sài', 'ใส่', ['put in', 'add', 'to put', 'wear', 'with (an ingredient)'], 'v', ['ordering'], 'sài prík = with chilli. Also "to wear".'],
  ['mâi sài', 'ไม่ใส่', ['without', 'do not add', 'no (ingredient)', 'do not put'], 'expr', ['ordering'], 'mâi sài prík = no chilli.'],
  ['ao glàp bâan', 'เอากลับบ้าน', ['take away', 'takeaway', 'to go', 'take home', 'I will take it home'], 'expr', ['ordering'], 'Literally "take back home".'],
  ['tîi nîi', 'ที่นี่', ['here', 'eat here', 'at this place'], 'expr', ['ordering'], 'gin tîi nîi = eat here.'],
  ['yang', 'ยัง', ['yet', 'still', 'not yet'], 'adv', [], 'gin kâao rụ̌ụ yang: have you eaten yet. The second greeting.'],
  ['gəən', 'เกิน', ['too', 'over', 'exceed'], 'v', [], 'wǎan gəən bpai: too sweet.'],
])
