import { words } from '../build'

export default words(8, [
  ['yàak', 'อยาก', ['want', 'to want'], 'v', ['modal']],
  ['yàak dâi', 'อยากได้', ['want to have', 'would like'], 'v', ['modal']],
  ['dtɔ̂ng', 'ต้อง', ['must', 'have to', 'need to'], 'v', ['modal']],
  ['dtɔ̂ng gaan', 'ต้องการ', ['need', 'to need', 'require'], 'v', ['modal']],
  ['kuan', 'ควร', ['should', 'ought to'], 'v', ['modal']],
  ['wǎi', 'ไหว', ['can manage', 'can handle', 'up to it'], 'v', ['modal']],
  ['mâi wǎi', 'ไม่ไหว', ['cannot manage', 'too much', 'I cannot'], 'expr', ['modal']],
  ['lɔɔng', 'ลอง', ['try', 'to try'], 'v', ['modal']],
  ['àat', 'อาจ', ['might', 'may', 'perhaps'], 'adv', ['modal']],
  ['àat jà', 'อาจจะ', ['maybe', 'might', 'perhaps'], 'adv', ['modal']],
  ['nε̂ε', 'แน่', ['sure', 'certain', 'for sure'], 'adj', ['modal']],
  ['nε̂ε nɔɔn', 'แน่นอน', ['of course', 'certainly', 'definitely'], 'adv', ['modal']],
  ['dtɔ̂ng gaan mái', 'ต้องการไหม', ['do you need it', 'do you want it']],
  ['à-nú-yâat', 'อนุญาต', ['allow', 'permission', 'permit'], 'v', ['modal']],
  ['hâam', 'ห้าม', ['forbidden', 'do not', 'must not'], 'v', ['modal']],
  ['wáng', 'หวัง', ['hope', 'to hope'], 'v', ['modal']],
  ['dtâng jai', 'ตั้งใจ', ['intend', 'mean to', 'pay attention'], 'v', ['modal']],
  ['pɔɔ', 'พอ', ['enough', 'sufficient'], 'adj', ['modal']],
  ['mâi pɔɔ', 'ไม่พอ', ['not enough'], 'expr', ['modal']],
  ['sǎa-mâat', 'สามารถ', ['can', 'be able to', 'capable'], 'v', ['modal']],
  ['jam bpen', 'จำเป็น', ['necessary', 'have to', 'essential'], 'adj', ['modal']],
  ['yàak rúu', 'อยากรู้', ['curious', 'want to know'], 'v', ['modal']],
  ['yàak gin', 'อยากกิน', ['want to eat', 'hungry for'], 'v', ['modal']],
  ['yàak bpai', 'อยากไป', ['want to go'], 'v', ['modal']],
  ['dtɔ̂ng rîip', 'ต้องรีบ', ['must hurry', 'have to rush'], 'expr', ['modal']],
  ['rîip', 'รีบ', ['hurry', 'to hurry', 'in a rush'], 'v', ['modal']],
  ['tîao', 'เที่ยว', ['go out', 'travel', 'trip'], 'v', ['modal']],
])
