import { words } from '../build'

export default words(2, [
  // verbs
  ['tam', 'ทำ', ['do', 'to do', 'make', 'to make'], 'v', ['verb']],
  ['hâi', 'ให้', ['give', 'to give', 'let', 'for'], 'v', ['verb']],
  ['duu', 'ดู', ['look', 'watch', 'to watch', 'to look', 'see (a film)'], 'v', ['verb']],
  ['hěn', 'เห็น', ['see', 'to see'], 'v', ['verb']],
  ['fang', 'ฟัง', ['listen', 'to listen', 'hear'], 'v', ['verb']],
  ['àan', 'อ่าน', ['read', 'to read'], 'v', ['verb']],
  ['kǐan', 'เขียน', ['write', 'to write'], 'v', ['verb']],
  ['rian', 'เรียน', ['study', 'to study', 'learn', 'to learn'], 'v', ['verb']],
  ['sɔ̌ɔn', 'สอน', ['teach', 'to teach'], 'v', ['verb']],
  ['tam-ngaan', 'ทำงาน', ['work', 'to work'], 'v', ['verb']],
  ['nɔɔn', 'นอน', ['sleep', 'to sleep', 'lie down', 'go to bed'], 'v', ['verb']],
  ['dtʉ̀ʉn', 'ตื่น', ['wake up', 'to wake up', 'wake'], 'v', ['verb']],
  ['nâng', 'นั่ง', ['sit', 'to sit', 'sit down'], 'v', ['verb']],
  ['yʉʉn', 'ยืน', ['stand', 'to stand', 'stand up'], 'v', ['verb']],
  ['dəən', 'เดิน', ['walk', 'to walk'], 'v', ['verb']],
  ['wîng', 'วิ่ง', ['run', 'to run'], 'v', ['verb']],
  ['kàp', 'ขับ', ['drive', 'to drive'], 'v', ['verb']],
  ['kìi', 'ขี่', ['ride', 'to ride'], 'v', ['verb']],
  ['kǎai', 'ขาย', ['sell', 'to sell'], 'v', ['verb']],
  ['jàai', 'จ่าย', ['pay', 'to pay'], 'v', ['verb']],
  ['rák', 'รัก', ['love', 'to love'], 'v', ['verb']],
  ['chɔ̂ɔp', 'ชอบ', ['like', 'to like', 'enjoy'], 'v', ['verb']],
  ['kít', 'คิด', ['think', 'to think'], 'v', ['verb']],
  ['jam', 'จำ', ['remember', 'to remember'], 'v', ['verb']],
  ['hǎa', 'หา', ['look for', 'to look for', 'search', 'find', 'seek'], 'v', ['verb']],
  ['tǎam', 'ถาม', ['ask', 'to ask'], 'v', ['verb']],
  ['dtɔ̀ɔp', 'ตอบ', ['answer', 'to answer', 'reply'], 'v', ['verb']],
  ['bɔ̀ɔk', 'บอก', ['tell', 'to tell', 'say'], 'v', ['verb']],
  ['lên', 'เล่น', ['play', 'to play'], 'v', ['verb']],
  ['rɔ́ɔng pleeng', 'ร้องเพลง', ['sing', 'to sing', 'sing a song'], 'v', ['verb']],
  ['dtên', 'เต้น', ['dance', 'to dance'], 'v', ['verb']],
  ['wâai náam', 'ว่ายน้ำ', ['swim', 'to swim'], 'v', ['verb']],
  ['tam aa-hǎan', 'ทำอาหาร', ['cook', 'to cook', 'make food'], 'v', ['verb']],
  ['bpə̀ət', 'เปิด', ['open', 'to open', 'turn on', 'switch on'], 'v', ['verb']],
  ['bpìt', 'ปิด', ['close', 'to close', 'turn off', 'switch off', 'shut'], 'v', ['verb']],
  ['sòng', 'ส่ง', ['send', 'to send', 'deliver'], 'v', ['verb']],
  ['ráp', 'รับ', ['receive', 'to receive', 'pick up', 'accept', 'get'], 'v', ['verb']],
  ['glàp', 'กลับ', ['return', 'to return', 'go back', 'come back'], 'v', ['verb']],
  ['tǔng', 'ถึง', ['arrive', 'to arrive', 'reach', 'until', 'to (a place)'], 'v', ['verb']],
  ['ɔ̀ɔk', 'ออก', ['exit', 'go out', 'to go out', 'leave', 'out'], 'v', ['verb']],
  ['yùt', 'หยุด', ['stop', 'to stop'], 'v', ['verb']],
  ['rə̂əm', 'เริ่ม', ['start', 'to start', 'begin'], 'v', ['verb']],
  ['sèt', 'เสร็จ', ['finish', 'finished', 'done', 'to finish', 'ready'], 'v', ['verb']],
  ['gèng', 'เก่ง', ['good at', 'skilled', 'clever', 'be good at', 'great (at something)'], 'adj', [], 'rian gèng: good at studying. The name of this app.'],
  ['gan', 'กัน', ['together', 'each other', 'one another'], 'adv', [], 'After the verb: gin kâao gan = eat together.'],
  // pronouns and pointers
  ['pûak-kǎo', 'พวกเขา', ['they', 'them'], 'pron', ['pronoun']],
  ['pûak-rao', 'พวกเรา', ['we', 'us', 'all of us'], 'pron', ['pronoun']],
  ['man', 'มัน', ['it'], 'pron', ['pronoun'], 'For things and animals. Rude for people.'],
  ['nîi', 'นี่', ['this', 'this one', 'here (this)'], 'pron', ['pointer'], 'Standing alone: nîi à-rai = what is this.'],
  ['níi', 'นี้', ['this', 'this (one)'], 'adj', ['pointer'], 'After a noun: kon níi = this person.'],
  ['nân', 'นั่น', ['that', 'that one'], 'pron', ['pointer']],
  ['nán', 'นั้น', ['that', 'that (one)'], 'adj', ['pointer'], 'After a noun: an nán = that one.'],
  ['nôon', 'โน่น', ['that over there', 'over there', 'yonder'], 'pron', ['pointer']],
  ['tîi', 'ที่', ['at', 'place', 'that (which)', 'in (a place)'], 'prep', [], 'The word that does three jobs: at, place, and the relative "that".'],
  // things to have and do things with
  ['kɔ̌ɔng', 'ของ', ['thing', 'things', 'of', 'belonging to', 'stuff'], 'n', []],
  ['nǎng-sʉ̌ʉ', 'หนังสือ', ['book'], 'n', ['thing']],
  ['rót', 'รถ', ['car', 'vehicle'], 'n', ['thing']],
  ['bâan', 'บ้าน', ['house', 'home'], 'n', ['place']],
  ['ngən', 'เงิน', ['money', 'silver'], 'n', ['thing']],
  ['too-rá-sàp', 'โทรศัพท์', ['phone', 'telephone', 'mobile phone'], 'n', ['thing']],
  ['pleeng', 'เพลง', ['song', 'music'], 'n', ['thing']],
  ['nǎng', 'หนัง', ['movie', 'film', 'leather'], 'n', ['thing']],
  ['gaa-fεε', 'กาแฟ', ['coffee'], 'n', ['food']],
  ['bia', 'เบียร์', ['beer'], 'n', ['food']],
  ['pʉ̂an', 'เพื่อน', ['friend'], 'n', ['people']],
  ['grung-têep', 'กรุงเทพ', ['Bangkok'], 'n', ['place'], 'City of angels. Nobody in Bangkok says "Bangkok".'],
  ['rúu-jàk', 'รู้จัก', ['know a person', 'be acquainted', 'to know (someone)'], 'v', ['verb'], 'People, not facts. Facts are rúu.'],
  ['mâi rúu-jàk', 'ไม่รู้จัก', ['do not know (a person)', 'I do not know them'], 'v', ['verb']],
])
