import { words } from '../build'

export default words(13, [
  ['bprà-chum', 'ประชุม', ['meeting'], 'n', ['work']],
  ['ɔ́ɔp-fít', 'ออฟฟิศ', ['office', 'the office'], 'n', ['work'], 'The everyday loanword. sǎm-nák-ngaan is the formal one.'],
  ['sǎm-nák-ngaan', 'สำนักงาน', ['office (formal)', 'bureau'], 'n', ['work']],
  ['nâa tîi', 'หน้าที่', ['duty', 'responsibility'], 'n', ['work']],
  ['ngaan#2', 'งาน', ['work', 'job', 'event'], 'n', ['work']],
  ['naai jâang', 'นายจ้าง', ['boss', 'employer'], 'n', ['work']],
  ['lûuk nɔ́ɔng', 'ลูกน้อง', ['subordinate', 'staff'], 'n', ['work']],
  ['lûuk kâa', 'ลูกค้า', ['customer', 'client'], 'n', ['work']],
  ['ii-meen', 'อีเมล', ['email'], 'n', ['work']],
  ['in-təə-nét', 'อินเทอร์เน็ต', ['internet'], 'n', ['work']],
  ['wép', 'เว็บ', ['web', 'website'], 'n', ['work']],
  ['kom-piw-dtəə', 'คอมพิวเตอร์', ['computer'], 'n', ['work']],
  ['dtaam', 'ตาม', ['follow', 'according to'], 'v', ['work']],
  ['waang', 'วาง', ['put down', 'place', 'plan'], 'v', ['work']],
  ['waang pεεn', 'วางแผน', ['to plan', 'make a plan'], 'v', ['work']],
  ['pεεn', 'แผน', ['plan'], 'n', ['work']],
  ['hǔa nâa', 'หัวหน้า', ['boss', 'head', 'chief'], 'n', ['work']],
  ['rát-tà-baan', 'รัฐบาล', ['government'], 'n', ['work']],
  ['gòt', 'กฎ', ['rule', 'law'], 'n', ['work']],
  ['bɔɔ-rí-sàt', 'บริษัท', ['company'], 'n', ['work']],
  ['ngən dụan', 'เงินเดือน', ['salary'], 'n', ['work']],
  ['laa', 'ลา', ['take leave', 'day off'], 'v', ['work']],
  ['wan yùt', 'วันหยุด', ['holiday', 'day off'], 'n', ['work']],
  ['rian nǎng-sụ̌ụ', 'เรียนหนังสือ', ['study', 'be in school'], 'v', ['work']],
  ['krùu', 'ครู', ['teacher'], 'n', ['work']],
  ['nák-rian', 'นักเรียน', ['student'], 'n', ['work']],
  ['roong-rian', 'โรงเรียน', ['school'], 'n', ['work']],
  ['má-hǎa-wít-tá-yaa-lai', 'มหาวิทยาลัย', ['university'], 'n', ['work']],
  ['gaan bâan', 'การบ้าน', ['homework'], 'n', ['work']],
  ['sɔ̌ɔp', 'สอบ', ['exam', 'to take an exam'], 'v', ['work']],
  ['pàan', 'ผ่าน', ['pass', 'to pass'], 'v', ['work']],
  ['dtòk', 'ตก', ['fail', 'fall'], 'v', ['work']],
  ['gàp', 'กับ', ['with'], 'prep', ['work']],
])
