import { words } from '../build'

export default words(12, [
  ['rúu-sʉ̀k', 'รู้สึก', ['feel', 'to feel'], 'v', ['feel']],
  ['bpùai', 'ป่วย', ['ill', 'sick'], 'adj', ['feel']],
  ['jèp', 'เจ็บ', ['hurt', 'in pain', 'painful'], 'v', ['feel']],
  ['nʉ̀ai', 'เหนื่อย', ['tired'], 'adj', ['feel']],
  ['bʉ̀a', 'เบื่อ', ['bored'], 'adj', ['feel']],
  ['glua#2', 'กลัว', ['afraid', 'scared', 'to fear'], 'v', ['feel']],
  ['dii jai', 'ดีใจ', ['glad', 'happy'], 'adj', ['feel']],
  ['dtà-lòk', 'ตลก', ['funny', 'a joke'], 'adj', ['feel']],
  ['sǐa jai', 'เสียใจ', ['sad', 'sorry', 'regret'], 'adj', ['feel']],
  ['gròot', 'โกรธ', ['angry'], 'adj', ['feel']],
  ['ngong', 'งง', ['confused'], 'adj', ['feel']],
  ['bplὲεk', 'แปลก', ['strange', 'weird'], 'adj', ['feel']],
  ['gang-won', 'กังวล', ['worried', 'anxious'], 'adj', ['feel']],
  ['mâi sà-baai', 'ไม่สบาย', ['unwell', 'not well'], 'adj', ['feel']],
  ['pέε', 'แพ้', ['allergic', 'lose'], 'v', ['feel']],
  ['mɔ̌ɔ', 'หมอ', ['doctor'], 'n', ['feel']],
  ['roong-pá-yaa-baan', 'โรงพยาบาล', ['hospital'], 'n', ['feel']],
  ['ráan yaa', 'ร้านยา', ['pharmacy'], 'n', ['feel']],
  ['bpùat', 'ปวด', ['ache', 'hurt', 'have a pain'], 'v', ['feel']],
  ['bpùat hǔa', 'ปวดหัว', ['headache', 'head hurts'], 'expr', ['feel']],
  ['bpùat tɔ́ɔng', 'ปวดท้อง', ['stomachache', 'stomach hurts'], 'expr', ['feel']],
  ['tɔ́ɔng', 'ท้อง', ['stomach', 'belly'], 'n', ['feel']],
  ['hǔa', 'หัว', ['head'], 'n', ['feel']],
  ['kε̌εn', 'แขน', ['arm'], 'n', ['feel']],
  ['kǎa', 'ขา', ['leg'], 'n', ['feel']],
  ['mʉʉ', 'มือ', ['hand'], 'n', ['feel']],
  ['hǔu', 'หู', ['ear'], 'n', ['feel']],
  ['jà-mùuk', 'จมูก', ['nose'], 'n', ['feel']],
  ['bpàak', 'ปาก', ['mouth'], 'n', ['feel']],
  ['fan', 'ฟัน', ['tooth', 'teeth'], 'n', ['feel']],
  ['kâi', 'ไข้', ['fever'], 'n', ['feel']],
  ['wàt', 'หวัด', ['cold', 'a cold'], 'n', ['feel']],
  ['ai', 'ไอ', ['cough', 'to cough'], 'v', ['feel']],
  ['táng', 'ทั้ง', ['all', 'whole', 'both'], 'adv', ['feel']],
])
