import { words } from '../build'

export default words(15, [
  ['tâa', 'ถ้า', ['if'], 'conj', ['link']],
  ['prɔ́', 'เพราะ', ['because'], 'conj', ['link']],
  ['prɔ́ wâa', 'เพราะว่า', ['because'], 'conj', ['link']],
  ['dtὲε', 'แต่', ['but'], 'conj', ['link']],
  ['lέ', 'และ', ['and'], 'conj', ['link']],
  ['gɔ̂', 'ก็', ['then', 'also', 'so'], 'adv', ['link']],
  ['ləəi', 'เลย', ['so', 'at all', 'altogether'], 'adv', ['link']],
  ['tîi#2', 'ที่', ['that[, which]', 'which'], 'conj', ['link']],
  ['hàak', 'หาก', ['if, formal', 'if', 'in case'], 'conj', ['link']],
  ['dtὲε wâa', 'แต่ว่า', ['but', 'however'], 'conj', ['link']],
  ['rʉ̌ʉ wâa', 'หรือว่า', ['or', 'or perhaps'], 'conj', ['link']],
  ['dang nán', 'ดังนั้น', ['therefore', 'so'], 'adv', ['link']],
  ['nɔ̂ɔk jàak', 'นอกจาก', ['besides', 'apart from'], 'prep', ['link']],
  ['pʉ̂a', 'เพื่อ', ['in order to', 'for'], 'prep', ['link']],
  ['dooi', 'โดย', ['by', 'by means of'], 'prep', ['link']],
  ['dtaam tîi', 'ตามที่', ['according to', 'as'], 'conj', ['link']],
  ['mέε wâa', 'แม้ว่า', ['even if', 'although'], 'conj', ['link']],
  ['dtὲε gɔ̂', 'แต่ก็', ['but still'], 'adv', ['link']],
  ['gɔ̂ dtaam', 'ก็ตาม', ['even so', 'whatever'], 'adv', ['link']],
  ['nʉ̂ang jàak', 'เนื่องจาก', ['due to', 'because of'], 'conj', ['link']],
  ['sʉ̂ng', 'ซึ่ง', ['which', 'that'], 'conj', ['link']],
  ['kʉʉ', 'คือ', ['is', 'namely', 'that is'], 'v', ['link']],
  ['rá-wàang', 'ระหว่าง', ['between'], 'prep', ['link']],
  ['táng níi', 'ทั้งนี้', ['in this regard'], 'adv', ['link']],
  ['táng nán', 'ทั้งนั้น', ['all of them', 'every one', 'without exception'], 'adv', ['link'], 'dii táng nán: they are all good.'],
  ['tîi jà', 'ที่จะ', ['that will'], 'conj', ['link']],
  ['jàak tîi', 'จากที่', ['from what'], 'conj', ['link']],
  ['pɔɔ tîi', 'พอที่', ['enough to'], 'conj', ['link']],
  ['yàang', 'อย่าง', ['kind', 'way', 'like', 'example'], 'n', ['link'], 'ìik yàang: another thing. yàang-rai: how.'],
  ['dtaam nán', 'ตามนั้น', ['accordingly', 'like that'], 'adv', ['link']],
])
