import { words } from '../build'

export default words(20, [
  ['jai yen', 'ใจเย็น', ['calm', 'cool-hearted', 'patient'], 'adj', ['heart']],
  ['lɔɔi', 'ลอย', ['float', 'to float'], 'v', ['heart']],
  ['sûu', 'สู้', ['fight', 'to fight', 'face up to'], 'v', ['heart']],
  ['sʉ̌a', 'เสือ', ['tiger'], 'n', ['heart']],
  ['nám jai', 'น้ำใจ', ['kindness', 'generosity'], 'n', ['heart']],
  ['tam bun', 'ทำบุญ', ['make merit'], 'v', ['heart']],
  ['sǐa nám jai', 'เสียน้ำใจ', ['feel let down', 'be hurt', 'lose heart'], 'v', ['heart'], 'When the kindness you gave is not returned.'],
  ['waang jai', 'วางใจ', ['trust', 'put one\'s heart down'], 'v', ['heart']],
  ['wái jai', 'ไว้ใจ', ['trust'], 'v', ['heart']],
  ['dtòk jai', 'ตกใจ', ['be startled', 'shocked'], 'v', ['heart']],
  ['sà-baai jai', 'สบายใจ', ['relieved', 'at ease'], 'adj', ['heart']],
  ['mâi sà-baai jai', 'ไม่สบายใจ', ['uneasy', 'worried'], 'adj', ['heart']],
  ['bplìan jai', 'เปลี่ยนใจ', ['change one\'s mind'], 'v', ['heart']],
  ['wát', 'วัด', ['temple'], 'n', ['heart']],
  ['dtàt sǐn jai', 'ตัดสินใจ', ['decide'], 'v', ['heart']],
  ['jàp jai', 'จับใจ', ['touching'], 'adj', ['heart']],
  ['sǎm-kan', 'สำคัญ', ['important'], 'adj', ['heart']],
  ['jai gwâang', 'ใจกว้าง', ['generous', 'open-minded'], 'adj', ['heart']],
  ['jai dam', 'ใจดำ', ['cruel', 'black-hearted'], 'adj', ['heart']],
  ['kέεn jai', 'แค้นใจ', ['resentful'], 'adj', ['heart']],
  ['bplɔ̀ɔp jai', 'ปลอบใจ', ['comfort', 'console'], 'v', ['heart']],
  ['dtem jai', 'เต็มใจ', ['willing', 'glad to', 'wholeheartedly'], 'adj', ['heart']],
])
