import { words } from '../build'

export default words(14, [
  ['fǒn', 'ฝน', ['rain'], 'n', ['weather']],
  ['fǒn dtòk', 'ฝนตก', ['it is raining', 'rain falls'], 'expr', ['weather']],
  ['nǎao', 'หนาว', ['cold'], 'adj', ['weather']],
  ['rɔ́ɔn#2', 'ร้อน', ['hot'], 'adj', ['weather']],
  ['ún', 'อุ่น', ['warm'], 'adj', ['weather']],
  ['chúm', 'ชื้น', ['humid', 'damp'], 'adj', ['weather']],
  ['hε̂εng', 'แห้ง', ['dry'], 'adj', ['weather']],
  ['lóm', 'ลม', ['wind'], 'n', ['weather']],
  ['mêek', 'เมฆ', ['cloud'], 'n', ['weather']],
  ['dáat', 'แดด', ['sunlight', 'sun'], 'n', ['weather']],
  ['fáa', 'ฟ้า', ['sky'], 'n', ['weather']],
  ['fáa rɔ́ɔng', 'ฟ้าร้อง', ['thunder'], 'expr', ['weather']],
  ['fǎi fáa', 'ไฟฟ้า', ['lightning', 'electricity'], 'n', ['weather']],
  ['náam tûam', 'น้ำท่วม', ['flood'], 'n', ['weather']],
  ['taa-lee', 'ทะเล', ['sea', 'ocean'], 'n', ['place']],
  ['puu-kǎo', 'ภูเขา', ['mountain'], 'n', ['place']],
  ['mε̂ε náam', 'แม่น้ำ', ['river'], 'n', ['place']],
  ['gòk', 'เกาะ', ['island'], 'n', ['place']],
  ['paa', 'ป่า', ['forest'], 'n', ['place']],
  ['jang-wàt', 'จังหวัด', ['province'], 'n', ['place']],
  ['mụang#2', 'เมือง', ['city', 'town'], 'n', ['place']],
  ['bprà-têet tai', 'ประเทศไทย', ['Thailand'], 'n', ['place']],
  ['nák tɔ̂ng tîao', 'นักท่องเที่ยว', ['tourist'], 'n', ['place']],
  ['aa-gàat', 'อากาศ', ['weather', 'air'], 'n', ['weather']],
  ['rɔ́ɔn mâak', 'ร้อนมาก', ['very hot'], 'expr', ['weather']],
  ['lóm rεεng', 'ลมแรง', ['strong wind'], 'expr', ['weather']],
  ['nǎao mâak', 'หนาวมาก', ['very cold'], 'expr', ['weather']],
])
