import { words } from '../build'

export default words(10, [
  ['hɔ̂ng', 'ห้อง', ['room'], 'n', ['home']],
  ['hɔ̂ng nɔɔn', 'ห้องนอน', ['bedroom'], 'n', ['home']],
  ['hɔ̂ng krua', 'ห้องครัว', ['kitchen'], 'n', ['home']],
  ['hɔ̂ng nâng lên', 'ห้องนั่งเล่น', ['living room'], 'n', ['home']],
  ['prà-dtuu', 'ประตู', ['door'], 'n', ['home']],
  ['nâa-dtàang', 'หน้าต่าง', ['window'], 'n', ['home']],
  ['dtiang', 'เตียง', ['bed'], 'n', ['home']],
  ['dtó', 'โต๊ะ', ['table', 'desk'], 'n', ['home']],
  ['gâo-îi', 'เก้าอี้', ['chair'], 'n', ['home']],
  ['dtûu', 'ตู้', ['cabinet', 'cupboard'], 'n', ['home']],
  ['dtûu yen', 'ตู้เย็น', ['fridge', 'refrigerator'], 'n', ['home']],
  ['kréuang sák pâa', 'เครื่องซักผ้า', ['washing machine'], 'n', ['home']],
  ['sák pâa', 'ซักผ้า', ['wash clothes', 'do laundry'], 'v', ['home']],
  ['àap náam', 'อาบน้ำ', ['bathe', 'take a shower', 'shower'], 'v', ['home']],
  ['prεεng fan', 'แปรงฟัน', ['brush teeth'], 'v', ['home']],
  ['dtàt pǒm', 'ตัดผม', ['cut hair', 'get a haircut'], 'v', ['home']],
  ['rîat pâa', 'รีดผ้า', ['iron clothes'], 'v', ['home']],
  ['gwaat bâan', 'กวาดบ้าน', ['sweep the house'], 'v', ['home']],
  ['tùu bâan', 'ถูบ้าน', ['mop the house', 'mop'], 'v', ['home']],
  ['sụ̂a', 'เสื้อ', ['shirt', 'top'], 'n', ['home']],
  ['gaang-geeng', 'กางเกง', ['trousers', 'pants'], 'n', ['home']],
  ['grà-bproong', 'กระโปรง', ['skirt'], 'n', ['home']],
  ['rɔɔng táo', 'รองเท้า', ['shoes'], 'n', ['home']],
  ['grà-bpǎo', 'กระเป๋า', ['bag', 'handbag'], 'n', ['home']],
  ['sà-bùu', 'สบู่', ['soap'], 'n', ['home']],
  ['pâa chét dtua', 'ผ้าเช็ดตัว', ['towel'], 'n', ['home']],
  ['fai', 'ไฟ', ['light', 'electricity', 'fire'], 'n', ['home']],
  ['kréuang bpràp aa-gàat', 'เครื่องปรับอากาศ', ['air conditioner', 'aircon'], 'n', ['home']],
  ['tii-wii', 'ทีวี', ['television', 'TV'], 'n', ['home']],
  ['mɔ̂ɔng', 'หมอน', ['pillow'], 'n', ['home']],
  ['pâa hòm', 'ผ้าห่ม', ['blanket'], 'n', ['home']],
  ['kréuang nǔng', 'เครื่องนุ่งห่ม', ['clothes', 'clothing'], 'n', ['home']],
  ['sòm', 'ซ่อม', ['repair', 'to repair', 'fix'], 'v', ['home']],
  ['bpìt fai', 'ปิดไฟ', ['turn off the light'], 'v', ['home']],
  ['bpə̀ət fai', 'เปิดไฟ', ['turn on the light'], 'v', ['home']],
])
