import { words } from '../build'

export default words(5, [
  ['sìp-èt', 'สิบเอ็ด', ['eleven', '11'], 'num', ['number']],
  ['sìp-sɔ̌ɔng', 'สิบสอง', ['twelve', '12'], 'num', ['number']],
  ['sìp-sǎam', 'สิบสาม', ['thirteen', '13'], 'num', ['number']],
  ['sìp-sìi', 'สิบสี่', ['fourteen', '14'], 'num', ['number']],
  ['sìp-hâa', 'สิบห้า', ['fifteen', '15'], 'num', ['number']],
  ['sìp-hòk', 'สิบหก', ['sixteen', '16'], 'num', ['number']],
  ['sìp-jèt', 'สิบเจ็ด', ['seventeen', '17'], 'num', ['number']],
  ['sìp-bpὲεt', 'สิบแปด', ['eighteen', '18'], 'num', ['number']],
  ['sìp-gâo', 'สิบเก้า', ['nineteen', '19'], 'num', ['number']],
  ['yîi-sìp', 'ยี่สิบ', ['twenty', '20'], 'num', ['number']],
  ['yîi-sìp-èt', 'ยี่สิบเอ็ด', ['twenty-one', '21'], 'num', ['number']],
  ['sǎam-sìp', 'สามสิบ', ['thirty', '30'], 'num', ['number']],
  ['sìi-sìp', 'สี่สิบ', ['forty', '40'], 'num', ['number']],
  ['hâa-sìp', 'ห้าสิบ', ['fifty', '50'], 'num', ['number']],
  ['hòk-sìp', 'หกสิบ', ['sixty', '60'], 'num', ['number']],
  ['jèt-sìp', 'เจ็ดสิบ', ['seventy', '70'], 'num', ['number']],
  ['bpὲεt-sìp', 'แปดสิบ', ['eighty', '80'], 'num', ['number']],
  ['gâo-sìp', 'เก้าสิบ', ['ninety', '90'], 'num', ['number']],
  ['rɔ́ɔi', 'ร้อย', ['hundred', '100', 'one hundred'], 'num', ['number']],
  ['pan', 'พัน', ['thousand', '1000', 'one thousand'], 'num', ['number']],
  ['mʉ̀ʉn', 'หมื่น', ['ten thousand', '10000'], 'num', ['number']],
  ['sε̌εn', 'แสน', ['hundred thousand', '100000'], 'num', ['number']],
  ['láan', 'ล้าน', ['million', '1 million'], 'num', ['number']],
  ['sà-dtang', 'สตางค์', ['satang', 'cent'], 'n', ['money']],
  ['ngən tɔɔn', 'เงินทอน', ['change', 'change (money)'], 'n', ['money']],
  ['raa-kaa', 'ราคา', ['price', 'cost'], 'n', ['money']],
  ['dtǔa', 'ตั๋ว', ['ticket'], 'n', ['money']],
  ['moong', 'โมง', ['o\'clock', 'hour (daytime)'], 'n', ['time'], 'The six-hour clock. bàai sɔ̌ɔng moong is 2 p.m.'],
  ['tûm', 'ทุ่ม', ['o\'clock (evening)', 'hour after 6 p.m.'], 'n', ['time'], 'sɔ̌ɔng tûm is 8 p.m.'],
  ['dtii#2', 'ตี', ['o\'clock (night)', 'hour after midnight'], 'n', ['time'], 'dtii sɔ̌ɔng is 2 a.m. Same letters as "hit".'],
  ['chûa-moong', 'ชั่วโมง', ['hour', 'hours'], 'n', ['time']],
  ['naa-tii', 'นาที', ['minute', 'minutes'], 'n', ['time']],
  ['wí-naa-tii', 'วินาที', ['second', 'seconds'], 'n', ['time']],
  ['wee-laa', 'เวลา', ['time'], 'n', ['time']],
  ['cháao', 'เช้า', ['morning'], 'n', ['time']],
  ['bàai', 'บ่าย', ['afternoon'], 'n', ['time']],
  ['yen', 'เย็น', ['evening', 'cool'], 'n', ['time']],
  ['glaang kʉʉn', 'กลางคืน', ['night', 'at night', 'midnight hours'], 'n', ['time']],
  ['wan níi', 'วันนี้', ['today'], 'n', ['time']],
  ['mʉ̂a-waan', 'เมื่อวาน', ['yesterday'], 'n', ['time']],
  ['prûng-níi', 'พรุ่งนี้', ['tomorrow'], 'n', ['time']],
  ['wan jan', 'วันจันทร์', ['Monday'], 'n', ['day']],
  ['wan ang-kaan', 'วันอังคาร', ['Tuesday'], 'n', ['day']],
  ['wan pút', 'วันพุธ', ['Wednesday'], 'n', ['day']],
  ['wan pá-rʉ́-hàt', 'วันพฤหัส', ['Thursday'], 'n', ['day']],
  ['wan sùk', 'วันศุกร์', ['Friday'], 'n', ['day']],
  ['wan sǎo', 'วันเสาร์', ['Saturday'], 'n', ['day']],
  ['wan aa-tít', 'วันอาทิตย์', ['Sunday'], 'n', ['day']],
  ['aa-tít', 'อาทิตย์', ['week', 'Sunday (short)'], 'n', ['time']],
  ['dʉan', 'เดือน', ['month'], 'n', ['time']],
  ['wan gə̀ət', 'วันเกิด', ['birthday'], 'n', ['time']],
  ['dtɔɔn cháao', 'ตอนเช้า', ['in the morning', 'morning time'], 'n', ['time']],
  ['dtɔɔn yen', 'ตอนเย็น', ['in the evening', 'evening time'], 'n', ['time']],
  ['wan', 'วัน', ['day', 'days'], 'n', ['time']],
  ['wâang', 'ว่าง', ['free', 'available', 'empty'], 'adj', ['time']],
  ['tɔɔn', 'ทอน', ['give change', 'to give change', 'change (money)'], 'v', ['money'], 'mâi dtɔ̂ng tɔɔn: keep the change.'],
  ['jà', 'จะ', ['will', 'going to', 'about to'], 'adv', ['aspect']],
])
