import { words } from '../build'

export default words(7, [
  ['gam-lang', 'กำลัง', ['in the middle of', 'currently', 'in the process of'], 'adv', ['aspect']],
  ['kəəi', 'เคย', ['ever', 'used to'], 'adv', ['aspect']],
  ['dtɔɔn', 'ตอน', ['when', 'at the time', 'period'], 'n', ['time']],
  ['dtɔɔn níi', 'ตอนนี้', ['now', 'at this moment'], 'adv', ['time']],
  ['dtɔɔn nán', 'ตอนนั้น', ['then', 'at that time'], 'adv', ['time']],
  ['mʉ̂a', 'เมื่อ', ['when', 'when (in the past)'], 'conj', ['time']],
  ['mʉ̂a gɔ̀ɔn', 'เมื่อก่อน', ['before', 'in the past', 'formerly'], 'adv', ['time']],
  ['jàak nán', 'จากนั้น', ['after that', 'then'], 'adv', ['time']],
  ['sùt táai', 'สุดท้าย', ['finally', 'in the end', 'last'], 'adv', ['time']],
  ['naan', 'นาน', ['a long time', 'long'], 'adv', ['time']],
  ['bɔ̀i', 'บ่อย', ['often', 'frequently'], 'adv', ['time']],
  ['túk wan', 'ทุกวัน', ['every day', 'everyday'], 'adv', ['time']],
  ['túk dʉan', 'ทุกเดือน', ['every month'], 'adv', ['time']],
  ['túk bpii', 'ทุกปี', ['every year'], 'adv', ['time']],
  ['wan lá', 'วันละ', ['per day', 'a day'], 'adv', ['time']],
  ['yang mâi', 'ยังไม่', ['not yet'], 'adv', ['aspect']],
  ['pə̂ng', 'เพิ่ง', ['just', 'just now', 'only just'], 'adv', ['aspect']],
  ['túk kráng', 'ทุกครั้ง', ['every time'], 'adv', ['time']],
  ['dtɔɔn rε̂εk', 'ตอนแรก', ['at first', 'in the beginning'], 'adv', ['time']],
  ['lǎng jàak', 'หลังจาก', ['after'], 'prep', ['time']],
  ['gɔ̀ɔn nâa', 'ก่อนหน้า', ['previously', 'beforehand'], 'adv', ['time']],
  ['dǐao níi', 'เดี๋ยวนี้', ['right now', 'nowadays', 'these days'], 'adv', ['time']],
  ['dǐao', 'เดี๋ยว', ['in a moment', 'wait', 'soon'], 'adv', ['time']],
  ['kráng nâa', 'ครั้งหน้า', ['next time'], 'adv', ['time']],
  ['kráng gɔ̀ɔn', 'ครั้งก่อน', ['last time', 'the previous time'], 'adv', ['time']],
  ['chiang-mài', 'เชียงใหม่', ['Chiang Mai'], 'n', ['place']],
  ['glaang wan', 'กลางวัน', ['daytime', 'midday'], 'n', ['time']],
  ['wan nâa', 'วันหน้า', ['a coming day', 'in the future'], 'n', ['time']],
  ['dʉan nâa', 'เดือนหน้า', ['next month'], 'n', ['time']],
  ['bpii nâa', 'ปีหน้า', ['next year'], 'n', ['time']],
  ['bpàt-jù-ban', 'ปัจจุบัน', ['now', 'the present'], 'n', ['time']],
  ['bpέp', 'แป๊บ', ['a moment', 'a sec'], 'n', ['time']],
  ['nʉng', 'นึง', ['one, said fast', 'one'], 'num', ['time'], 'nʉ̀ng as it is said after another word: bpέp nʉng.'],
])
