import { words } from '../build'

export default words(1, [
  ['sà-wàt-dii', 'สวัสดี', ['hello', 'hi', 'goodbye', 'good day'], 'expr', ['greeting']],
  ['kráp', 'ครับ', ['polite particle[, male]', '(male) polite particle', 'yes (male)'], 'particle', ['polite'], 'Ends almost every sentence a man says politely. Alone it means "yes".'],
  ['kâ', 'ค่ะ', ['polite particle[, female]', '(female) polite particle', 'yes (female)'], 'particle', ['polite'], 'Female polite ending for statements. Alone it means "yes".'],
  ['ká', 'คะ', ['polite particle[, female, asking]', '(female) question particle'], 'particle', ['polite'], 'Female polite ending for questions: sà-baai dii mái ká.'],
  ['kɔ̀ɔp kun', 'ขอบคุณ', ['thank you', 'thanks'], 'expr', ['polite']],
  ['kɔ̌ɔ tôot', 'ขอโทษ', ['sorry', 'excuse me', 'I am sorry', 'apologies'], 'expr', ['polite']],
  ['châi', 'ใช่', ['yes', 'correct', 'right', 'that is right', 'true'], 'expr', ['yes-no']],
  ['mâi châi', 'ไม่ใช่', ['no', 'not correct', 'wrong', 'that is not right', 'is not'], 'expr', ['yes-no']],
  ['pǒm', 'ผม', ['I, male speaker', 'I', 'me', 'I (male)', 'I (male speaker)'], 'pron', ['pronoun'], 'Male speaker. Also means "hair".'],
  ['chǎn', 'ฉัน', ['I, female speaker', 'I', 'me', 'I (female)', 'I (female speaker)'], 'pron', ['pronoun'], 'Female speaker, or intimate for anyone. Said chán (high) in everyday speech.'],
  ['kun', 'คุณ', ['you'], 'pron', ['pronoun'], 'Polite "you", also the title before a first name.'],
  ['rao', 'เรา', ['we', 'us'], 'pron', ['pronoun'], 'Also a casual "I" among friends.'],
  ['dii', 'ดี', ['good', 'well', 'fine', 'nice'], 'adj', []],
  ['sà-baai', 'สบาย', ['comfortable', 'well', 'relaxed', 'fine', 'at ease'], 'adj', []],
  ['sà-baai dii', 'สบายดี', ['fine', 'I am fine', 'well', 'doing well', 'I am well'], 'expr', ['greeting']],
  ['chûai', 'ช่วย', ['help', 'to help', 'please (do)'], 'v', []],
  ['dâi', 'ได้', ['can', 'ok', 'able to', 'get', 'yes you can', 'possible'], 'v', ['modal']],
  ['mâi dâi', 'ไม่ได้', ['cannot', 'can not', 'not possible', 'no (you cannot)', 'did not'], 'expr', ['modal']],
  ['bpen', 'เป็น', ['to be', 'be', 'is', 'am', 'are'], 'v', []],
  ['yùu', 'อยู่', ['to be at', 'be located', 'stay', 'live', 'is at', 'be (somewhere)'], 'v', []],
  ['mii', 'มี', ['have', 'to have', 'there is', 'there are', 'has'], 'v', []],
  ['kɔ̌ɔ', 'ขอ', ['may I have', 'ask for', 'request', 'can I have', 'I would like'], 'v', ['polite'], 'kɔ̌ɔ + thing + nɔ̀i = the polite way to ask for anything.'],
  ['nɔ̀i', 'หน่อย', ['a little', 'a bit', 'please (softener)', 'a little bit'], 'particle', ['softener'], 'Softens a request: kɔ̌ɔ náam nɔ̀i.'],
  ['kâo jai', 'เข้าใจ', ['understand', 'to understand', 'I understand'], 'v', [], 'Literally "enter heart".'],
  ['mâi kâo jai', 'ไม่เข้าใจ', ['do not understand', 'I do not understand'], 'expr', []],
  ['pûut', 'พูด', ['speak', 'to speak', 'say', 'talk'], 'v', []],
  ['paa-sǎa', 'ภาษา', ['language'], 'n', []],
  ['paa-sǎa tai', 'ภาษาไทย', ['Thai', 'Thai language', '(the) Thai language'], 'n', []],
  ['paa-sǎa ang-grìt', 'ภาษาอังกฤษ', ['English', 'English language', '(the) English language'], 'n', []],
  ['kon tai', 'คนไทย', ['Thai person', 'Thai people', 'Thai (person)', 'a Thai'], 'n', []],
  ['fà-ràng', 'ฝรั่ง', ['Westerner', 'foreigner', 'Western foreigner', 'white foreigner'], 'n', [], 'Also "guava". Not rude, just descriptive.'],
  ['chʉ̂ʉ', 'ชื่อ', ['name', 'to be named', 'be called'], 'n', [], 'Your name goes after it. pǒm chʉ̂ʉ …: my name is ….'],
  ['rúu', 'รู้', ['know', 'to know', 'know (a fact)'], 'v', []],
  ['mâi rúu', 'ไม่รู้', ['do not know', 'I do not know', 'dunno'], 'expr', []],
  ['mâak', 'มาก', ['very', 'a lot', 'much', 'very much', 'many'], 'adv', []],
  ['nít-nɔ̀i', 'นิดหน่อย', ['a little', 'a little bit', 'a bit', 'slightly'], 'adv', []],
  ['cháa', 'ช้า', ['slow', 'slowly', 'late'], 'adj', []],
  ['cháa cháa', 'ช้าๆ', ['slowly', 'nice and slow'], 'adv', [], 'Doubling softens it. Written with ๆ, the repeat mark.'],
  ['ìik', 'อีก', ['again', 'more', 'another', 'other'], 'adv', []],
  ['ìik kráng', 'อีกครั้ง', ['again', 'once more', 'one more time'], 'adv', []],
  ['aa-hǎan', 'อาหาร', ['food', 'meal', 'cuisine'], 'n', ['food']],
  ['náam', 'น้ำ', ['water'], 'n', ['food']],
  ['hɔ̂ng náam', 'ห้องน้ำ', ['toilet', 'bathroom', 'restroom'], 'n', ['place'], 'Literally "water room".'],
  ['chôok dii', 'โชคดี', ['good luck', 'lucky', 'take care'], 'expr', ['greeting'], 'Also the everyday goodbye.'],
  ['laa gɔ̀ɔn', 'ลาก่อน', ['goodbye', 'farewell'], 'expr', ['greeting'], 'Formal. Thais usually say bpai gɔ̀ɔn ná or chôok dii.'],
  ['yin-dii', 'ยินดี', ['glad', 'pleased', 'happy to', 'delighted'], 'adj', ['polite']],
  ['yin-dii tîi dâi rúu-jàk', 'ยินดีที่ได้รู้จัก', ['nice to meet you', 'pleased to meet you', 'glad to meet you'], 'expr', ['greeting']],
  // numbers 0–10 (nʉ̀ng is in level 0)
  ['sǔun', 'ศูนย์', ['zero', '0'], 'num', ['number']],
  ['sɔ̌ɔng', 'สอง', ['two', '2'], 'num', ['number']],
  ['sǎam', 'สาม', ['three', '3'], 'num', ['number']],
  ['sìi', 'สี่', ['four', '4'], 'num', ['number']],
  ['hâa', 'ห้า', ['five', '5'], 'num', ['number']],
  ['hòk', 'หก', ['six', '6'], 'num', ['number']],
  ['jèt', 'เจ็ด', ['seven', '7'], 'num', ['number']],
  ['bpὲεt', 'แปด', ['eight', '8'], 'num', ['number']],
  ['gâo', 'เก้า', ['nine', '9'], 'num', ['number']],
  ['sìp', 'สิบ', ['ten', '10'], 'num', ['number']],
  ['tai', 'ไทย', ['Thai'], 'adj', [], 'The country, the language, the people. kon tai, paa-sǎa tai.'],
  ['dûai', 'ด้วย', ['too', 'as well', 'with'], 'adv', [], 'After the verb: chûai dûai.'],
  ['rai', 'ไร', ['anything[, as in never mind]'], 'n', [], 'Almost only in mâi bpen rai.'],
  ['ná', 'นะ', ['softener', 'you know'], 'particle', ['softener'], 'Softens a statement. bpai gɔ̀ɔn ná.'],
  ['gɔ̀ɔn', 'ก่อน', ['first', 'before', 'ahead'], 'adv', [], 'bpai gɔ̀ɔn: I go first. The everyday goodbye.'],
])
