import { words } from '../build'

export default words(17, [
  ['sì', 'สิ', ['insist', 'do it'], 'particle', ['particle']],
  ['rə̌ə', 'เหรอ', ['oh really', 'is that so'], 'particle', ['particle']],
  ['rɔ̀k', 'หรอก', ['not at all', 'no way (soft)'], 'particle', ['particle']],
  ['já', 'จ๊ะ', ['close polite (female)', 'affectionate ending'], 'particle', ['particle']],
  ['jâa', 'จ้า', ['warm ending'], 'particle', ['particle']],
  ['wá', 'วะ', ['rough ending', 'buddy (rough)'], 'particle', ['particle']],
  ['há', 'ฮะ', ['casual male ending'], 'particle', ['particle']],
  ['ná há', 'นะฮะ', ['polite casual'], 'particle', ['particle']],
  ['ná ká', 'นะคะ', ['polite softener (female)', 'okay? (female)'], 'particle', ['particle']],
  ['ná kráp', 'นะครับ', ['polite softener (male)', 'okay? (male)'], 'particle', ['particle']],
  ['kráp pǒm', 'ครับผม', ['yes sir', 'certainly (male)'], 'particle', ['particle']],
  ['bpà', 'ปะ', ['right? (casual)', 'or not? (casual)'], 'particle', ['particle'], 'Short for rʉ̌ʉ bplào. Friends only.'],
  ['sì ná', 'สินะ', ['I guess', 'must be', 'so that is it'], 'particle', ['particle'], 'nʉ̀ai sì ná: you must be tired.'],
  ['ná sì', 'นะสิ', ['see? of course'], 'particle', ['particle']],
  ['ləəi ná', 'เลยนะ', ['really, you know'], 'particle', ['particle']],
  ['mâi rɔ̀k', 'ไม่หรอก', ['no, not at all'], 'expr', ['particle']],
  ['jang', 'จัง', ['so', 'really', 'very (casual)'], 'particle', ['particle'], 'à-rɔ̀i jang: so tasty. Among friends.'],
  ['ao sì', 'เอาสิ', ['go on then', 'do it then'], 'expr', ['particle']],
  ['bpai sì', 'ไปสิ', ['go on', 'go then'], 'expr', ['particle']],
  ['maa ná', 'มานะ', ['come, will you'], 'expr', ['particle']],
  ['dii ná', 'ดีนะ', ['good, you know', 'that is good']],
  ['mâi bpen rai ná', 'ไม่เป็นไรนะ', ['it is okay, really']],
  ['jing ná', 'จริงนะ', ['really', 'I mean it']],
  ['jing', 'จริง', ['true', 'real', 'really'], 'adj', ['particle']],
  ['jing jing', 'จริงๆ', ['really', 'truly', 'for real'], 'adv', ['particle'], 'Doubling it means you mean it. Written with ๆ, the repeat mark.'],
  ['máng', 'มั้ง', ['probably', 'I guess'], 'particle', ['particle'], 'At the end, a guess: kǎo mâi maa máng.'],
  ['tə̀', 'เถอะ', ['let us', 'go ahead'], 'particle', ['particle'], 'At the end, a nudge: bpai tə̀.'],
  ['nə́', 'เนอะ', ['right', 'is it not'], 'particle', ['particle'], 'At the end, asks you to agree: rɔ́ɔn nə́.'],
  ['ɔ̌ɔ', 'อ๋อ', ['oh, I see', 'oh'], 'particle', ['particle']],
  ['ngán', 'งั้น', ['in that case', 'then'], 'conj', ['particle']],
  ['oo-kee', 'โอเค', ['okay', 'OK'], 'expr', ['particle']],
])
