import { words } from '../build'

export default words(15, [
  ['tâa', 'ถ้า', ['if'], 'conj', ['link']],
  ['prɔ́', 'เพราะ', ['because'], 'conj', ['link']],
  ['prɔ́ wâa', 'เพราะว่า', ['because'], 'conj', ['link']],
  ['dtὲε', 'แต่', ['but'], 'conj', ['link']],
  ['lέ', 'และ', ['and'], 'conj', ['link']],
  ['gɔ̂', 'ก็', ['then', 'also', 'so'], 'adv', ['link']],
  ['ləəi', 'เลย', ['so', 'at all', 'altogether'], 'adv', ['link']],
  ['tîi#2', 'ที่', ['that (relative)', 'which'], 'conj', ['link']],
  ['hàak', 'หาก', ['if', 'in case'], 'conj', ['link']],
  ['dtὲε wâa', 'แต่ว่า', ['but', 'however'], 'conj', ['link']],
  ['rụ̌ụ wâa', 'หรือว่า', ['or', 'or perhaps'], 'conj', ['link']],
  ['dâng nán', 'ดังนั้น', ['therefore', 'so'], 'adv', ['link']],
  ['nɔ́k jàak', 'นอกจาก', ['besides', 'apart from'], 'prep', ['link']],
  ['pụ̂a', 'เพื่อ', ['in order to', 'for'], 'prep', ['link']],
  ['dôoi', 'โดย', ['by', 'by means of'], 'prep', ['link']],
  ['dtàam tîi', 'ตามที่', ['according to', 'as'], 'conj', ['link']],
  ['mέε wâa', 'แม้ว่า', ['even if', 'although'], 'conj', ['link']],
  ['dtὲε gɔ̂', 'แต่ก็', ['but still'], 'adv', ['link']],
  ['gɔ̂ dtàam', 'ก็ตาม', ['even so', 'whatever'], 'adv', ['link']],
  ['nụ̂ang jàak', 'เนื่องจาก', ['due to', 'because of'], 'conj', ['link']],
  ['sụ̂ng', 'ซึ่ง', ['which', 'that'], 'conj', ['link']],
  ['kụụ', 'คือ', ['is', 'namely', 'that is'], 'v', ['link']],
  ['rà-wàang', 'ระหว่าง', ['between'], 'prep', ['link']],
  ['táng nîi', 'ทั้งนี้', ['in this regard'], 'adv', ['link']],
  ['táng nán', 'ทั้งนั้น', ['even so'], 'adv', ['link']],
  ['tîi jà', 'ที่จะ', ['that will'], 'conj', ['link']],
  ['jàak tîi', 'จากที่', ['from what'], 'conj', ['link']],
  ['pɔɔ tîi', 'พอที่', ['enough to'], 'conj', ['link']],
  ['yàang', 'อย่าง', ['kind', 'way', 'like', 'example'], 'n', ['link'], 'ìik yàang: another thing. yàang-rai: how.'],
  ['dtàam nán', 'ตามนั้น', ['accordingly', 'like that'], 'adv', ['link']],
])
