import { words } from '../build'

export default words(11, [
  ['sǐi', 'สี', ['colour', 'color'], 'n', ['shop']],
  ['sǐi dεεng', 'สีแดง', ['red'], 'adj', ['colour']],
  ['sǐi nám ngən', 'สีน้ำเงิน', ['blue'], 'adj', ['colour']],
  ['sǐi kǐao', 'สีเขียว', ['green'], 'adj', ['colour']],
  ['sǐi lụ̌ang', 'สีเหลือง', ['yellow'], 'adj', ['colour']],
  ['sǐi sôm', 'สีส้ม', ['orange'], 'adj', ['colour']],
  ['sǐi mûang', 'สีม่วง', ['purple'], 'adj', ['colour']],
  ['sǐi nám dtaan', 'สีน้ำตาล', ['brown'], 'adj', ['colour']],
  ['sǐi dam', 'สีดำ', ['black'], 'adj', ['colour']],
  ['sǐi kǎao', 'สีขาว', ['white'], 'adj', ['colour']],
  ['sǐi chom-puu', 'สีชมพู', ['pink'], 'adj', ['colour']],
  ['lék', 'เล็ก', ['small'], 'adj', ['size']],
  ['yaao', 'ยาว', ['long'], 'adj', ['size']],
  ['sân', 'สั้น', ['short (length)'], 'adj', ['size']],
  ['kwâang', 'กว้าง', ['wide'], 'adj', ['size']],
  ['kε̂εp', 'แคบ', ['narrow'], 'adj', ['size']],
  ['lót', 'ลด', ['reduce', 'discount', 'come down'], 'v', ['shop']],
  ['lót raa-kaa', 'ลดราคา', ['on sale', 'discount the price'], 'expr', ['shop']],
  ['tɔ̀ɔ rɔɔng', 'ต่อรอง', ['bargain', 'to bargain'], 'v', ['shop']],
  ['tɔ̀ɔ', 'ต่อ', ['bargain', 'continue', 'connect'], 'v', ['shop']],
  ['kε̂ε', 'แค่', ['only', 'just', 'only as much as'], 'adv', ['shop']],
  ['sùan lót', 'ส่วนลด', ['discount'], 'n', ['shop']],
  ['káp', 'คับ', ['tight'], 'adj', ['shop']],
  ['lǔam', 'หลวม', ['loose'], 'adj', ['shop']],
  ['chút', 'ชุด', ['outfit', 'set', 'classifier for sets'], 'n', ['shop']],
  ['kan', 'คัน', ['classifier for vehicles'], 'clf', ['shop']],
  ['bai', 'ใบ', ['classifier for leaves, bags, sheets'], 'clf', ['shop']],
  ['kûu', 'คู่', ['pair', 'classifier for pairs'], 'clf', ['shop']],
  ['kε̂ε níi', 'แค่นี้', ['just this', 'only this much'], 'expr', ['shop']],
  ['lɔɔng sài', 'ลองใส่', ['try on'], 'v', ['shop']],
  ['pεεng bpai', 'แพงไป', ['too expensive'], 'expr', ['shop']],
  ['tùuk', 'ถูก', ['cheap', 'correct'], 'adj', ['shop']],
  ['ụ̀ụn', 'อื่น', ['other', 'another'], 'adj', ['shop']],
  ['sǐi fáa', 'สีฟ้า', ['sky blue', 'light blue'], 'adj', ['colour']],
])
