import { words } from '../build'

export default words(20, [
  ['nát', 'นัด', ['appointment', 'to make a date'], 'n', ['city']],
  ['kui', 'คุย', ['chat', 'to chat', 'talk'], 'v', ['city']],
  ['dtòk long', 'ตกลง', ['agree', 'deal'], 'v', ['city']],
  ['nát jəə', 'นัดเจอ', ['make a plan to meet'], 'v', ['city']],
  ['sà-tǎan-tîi', 'สถานที่', ['place', 'venue'], 'n', ['city']],
  ['baa', 'บาร์', ['bar'], 'n', ['city']],
  ['ráan gaa-fεε', 'ร้านกาแฟ', ['cafe', 'coffee shop'], 'n', ['city']],
  ['roong nǎng', 'โรงหนัง', ['cinema', 'movie theatre'], 'n', ['city']],
  ['kâao-sǎan', 'ข้าวสาร', ['Khao San'], 'n', ['city']],
  ['sǐi-lom', 'สีลม', ['Silom'], 'n', ['city']],
  ['sù-kǔm-wít', 'สุขุมวิท', ['Sukhumvit'], 'n', ['city']],
  ['jà-dtù-jàk', 'จตุจักร', ['Chatuchak'], 'n', ['city']],
  ['tε̌εo', 'แถว', ['area', 'row', 'neighbourhood'], 'n', ['city']],
  ['pûak', 'พวก', ['group', 'bunch'], 'n', ['city']],
  ['dtà-làat nát', 'ตลาดนัด', ['weekly market', 'weekend market', 'market fair'], 'n', ['city'], 'nát is the appointment: a market that meets on set days.'],
  ['kui lên', 'คุยเล่น', ['chat for fun'], 'v', ['city']],
  ['dtà-làat náam', 'ตลาดน้ำ', ['floating market'], 'n', ['city']],
  ['tîao glaang kʉʉn', 'เที่ยวกลางคืน', ['go out at night'], 'v', ['city']],
  ['nát wee-laa', 'นัดเวลา', ['set a time'], 'v', ['city']],
  ['yîam', 'เยี่ยม', ['visit', 'great'], 'v', ['city']],
  ['chom', 'ชม', ['appreciate', 'watch', 'praise'], 'v', ['city']],
  ['hǔa-rɔ́', 'หัวเราะ', ['laugh'], 'v', ['city']],
  ['dtὲng dtua', 'แต่งตัว', ['get dressed'], 'v', ['city']],
  ['gii-laa', 'กีฬา', ['sport', 'sports'], 'n', ['city']],
  ['lên gii-laa', 'เล่นกีฬา', ['play sports', 'do sport'], 'v', ['city']],
  ['bəə', 'เบอร์', ['phone number', 'number'], 'n', ['city']],
  ['too', 'โทร', ['call', 'to phone', 'ring'], 'v', ['city']],
  ['tàai rûup', 'ถ่ายรูป', ['take a photo', 'take a picture'], 'v', ['city']],
])
