import { words } from '../build'

export default words(12, [
  ['rúu-sụ̀k', 'รู้สึก', ['feel', 'to feel'], 'v', ['feel']],
  ['bpùai', 'ป่วย', ['ill', 'sick'], 'adj', ['feel']],
  ['jèp', 'เจ็บ', ['hurt', 'in pain', 'painful'], 'v', ['feel']],
  ['nụ̀ai', 'เหนื่อย', ['tired'], 'adj', ['feel']],
  ['bụ̀a', 'เบื่อ', ['bored'], 'adj', ['feel']],
  ['glua#2', 'กลัว', ['afraid', 'scared', 'to fear'], 'v', ['feel']],
  ['dii jai', 'ดีใจ', ['glad', 'happy'], 'adj', ['feel']],
  ['sǐa jai', 'เสียใจ', ['sad', 'sorry', 'regret'], 'adj', ['feel']],
  ['gròot', 'โกรธ', ['angry'], 'adj', ['feel']],
  ['ngûng', 'งง', ['confused'], 'adj', ['feel']],
  ['bplàaek', 'แปลก', ['strange', 'weird'], 'adj', ['feel']],
  ['gàng-won', 'กังวล', ['worried', 'anxious'], 'adj', ['feel']],
  ['mâi sà-baai', 'ไม่สบาย', ['unwell', 'not well'], 'adj', ['feel']],
  ['pε̂ε', 'แพ้', ['allergic', 'lose'], 'v', ['feel']],
  ['mɔ̌ɔ', 'หมอ', ['doctor'], 'n', ['feel']],
  ['roong-pá-yaa-baan', 'โรงพยาบาล', ['hospital'], 'n', ['feel']],
  ['ráan yaa', 'ร้านยา', ['pharmacy'], 'n', ['feel']],
  ['hǔa jèp', 'หัวเจ็บ', ['headache'], 'expr', ['feel']],
  ['bpùat hǔa', 'ปวดหัว', ['headache', 'head hurts'], 'expr', ['feel']],
  ['bpùat tɔ́ɔng', 'ปวดท้อง', ['stomachache', 'stomach hurts'], 'expr', ['feel']],
  ['tɔ́ɔng', 'ท้อง', ['stomach', 'belly'], 'n', ['feel']],
  ['hǔa', 'หัว', ['head'], 'n', ['feel']],
  ['kε̌εn', 'แขน', ['arm'], 'n', ['feel']],
  ['kǎa', 'ขา', ['leg'], 'n', ['feel']],
  ['mụụ', 'มือ', ['hand'], 'n', ['feel']],
  ['dtaa#2', 'ตา', ['eye'], 'n', ['feel']],
  ['hǔu', 'หู', ['ear'], 'n', ['feel']],
  ['jamùuk', 'จมูก', ['nose'], 'n', ['feel']],
  ['bpàak', 'ปาก', ['mouth'], 'n', ['feel']],
  ['fan', 'ฟัน', ['tooth', 'teeth'], 'n', ['feel']],
  ['kai', 'ไข้', ['fever'], 'n', ['feel']],
  ['wìat', 'หวัด', ['cold', 'a cold'], 'n', ['feel']],
  ['aai', 'ไอ', ['cough', 'to cough'], 'v', ['feel']],
])
