import { words } from '../build'

export default words(9, [
  ['krɔ̂ɔp-krua', 'ครอบครัว', ['family'], 'n', ['people']],
  ['pɔ̂ɔ', 'พ่อ', ['father', 'dad'], 'n', ['people']],
  ['mε̂ε', 'แม่', ['mother', 'mom', 'mum'], 'n', ['people']],
  ['lûuk', 'ลูก', ['child', 'kid', 'offspring'], 'n', ['people']],
  ['pîi', 'พี่', ['older sibling', 'older brother or sister', 'you, to someone a bit older'], 'n', ['people'], 'Also you, or I, between people a few years apart: a driver, a colleague.'],
  ['nɔ́ɔng', 'น้อง', ['younger sibling', 'younger brother or sister', 'you, to someone younger'], 'n', ['people'], 'Also how to call a waiter or a shop assistant.'],
  ['pûu-chaai', 'ผู้ชาย', ['man', 'male', 'boy'], 'n', ['people']],
  ['pûu-yǐng', 'ผู้หญิง', ['woman', 'female', 'girl'], 'n', ['people']],
  ['dèk', 'เด็ก', ['child', 'kid', 'children'], 'n', ['people']],
  ['kon gὲε', 'คนแก่', ['old person', 'elderly person'], 'n', ['people']],
  ['fεεn', 'แฟน', ['boyfriend', 'girlfriend', 'partner'], 'n', ['people']],
  ['sǎa-mii', 'สามี', ['husband'], 'n', ['people']],
  ['pan-rá-yaa', 'ภรรยา', ['wife'], 'n', ['people']],
  ['dtua', 'ตัว', ['classifier for animals', 'body', 'self'], 'clf', ['classifier']],
  ['kon#2', 'คน', ['classifier for people', 'person (classifier)'], 'clf', ['classifier']],
  ['sǔai', 'สวย', ['beautiful', 'pretty'], 'adj', ['describe']],
  ['lɔ̀ɔ', 'หล่อ', ['handsome'], 'adj', ['describe']],
  ['sǔung', 'สูง', ['tall', 'high'], 'adj', ['describe']],
  ['dtîa', 'เตี้ย', ['short[, in height]'], 'adj', ['describe']],
  ['ûan', 'อ้วน', ['fat', 'overweight'], 'adj', ['describe']],
  ['pɔ̌ɔm', 'ผอม', ['thin', 'slim'], 'adj', ['describe']],
  ['nùm', 'หนุ่ม', ['young man', 'young (male)'], 'n', ['people']],
  ['sǎao', 'สาว', ['young woman', 'young (female)'], 'n', ['people']],
  ['jai dii', 'ใจดี', ['kind', 'kind-hearted'], 'adj', ['describe']],
  ['jai rɔ́ɔn', 'ใจร้อน', ['impatient', 'hot-tempered'], 'adj', ['describe']],
  ['greeng jai', 'เกรงใจ', ['reluctant to impose'], 'v', ['describe'], 'The unwillingness to bother someone. A Thai social word.'],
  ['yài', 'ใหญ่', ['big', 'large'], 'adj', ['describe']],
  ['sà-nùk', 'สนุก', ['fun', 'enjoyable'], 'adj', ['describe']],
  ['nâa rák', 'น่ารัก', ['cute', 'lovely'], 'adj', ['describe']],
  ['nâa gin', 'น่ากิน', ['looks tasty', 'appetizing'], 'adj', ['describe']],
  ['nâa glua', 'น่ากลัว', ['scary', 'frightening'], 'adj', ['describe']],
  ['kε̌ng', 'แข็ง', ['hard', 'strong', 'tough'], 'adj', ['describe']],
  ['ɔ̀ɔn', 'อ่อน', ['soft', 'weak', 'young (of age)'], 'adj', ['describe']],
  ['mii kwaam sùk', 'มีความสุข', ['happy', 'be happy', 'content'], 'adj', ['describe'], 'Literally "have happiness". The everyday way to say happy.'],
  ['sòk-gà-bpròk', 'สกปรก', ['dirty'], 'adj', ['describe']],
  ['chà-làat', 'ฉลาด', ['clever', 'smart'], 'adj', ['describe']],
  ['ngôo', 'โง่', ['stupid', 'foolish'], 'adj', ['describe']],
  ['ngîap', 'เงียบ', ['quiet'], 'adj', ['describe']],
  ['sǐang dang', 'เสียงดัง', ['loud', 'noisy'], 'adj', ['describe']],
  ['lung', 'ลุง', ['uncle', "a parent's older brother", 'an older man'], 'n', ['people'], 'Older brother of either parent. Also any older man: a driver, a vendor.'],
  ['nǔu', 'หนู', ['I, a young woman speaking', 'you, to a child', 'mouse'], 'pron', ['people'], 'A girl or a young woman says nǔu for I to someone older. Also a mouse.'],
  ['kɔ̀ɔp jai', 'ขอบใจ', ['thanks, to someone younger', 'thanks'], 'expr', ['people'], 'Thanks from an elder to someone younger. To anyone older, kɔ̀ɔp kun.'],
])
