import { words } from '../build'

export default words(13, [
  ['bprà-chum', 'ประชุม', ['meeting'], 'n', ['work']],
  ['hɔ̂ng ngaan', 'ห้องงาน', ['office room'], 'n', ['work']],
  ['sǎa-mák-ngaan', 'สำนักงาน', ['office'], 'n', ['work']],
  ['nâa tîi', 'หน้าที่', ['duty', 'responsibility'], 'n', ['work']],
  ['ngaan#2', 'งาน', ['work', 'job', 'event'], 'n', ['work']],
  ['nâai jâang', 'นายจ้าง', ['boss', 'employer'], 'n', ['work']],
  ['lûuk nɔ́ɔng', 'ลูกน้อง', ['subordinate', 'staff'], 'n', ['work']],
  ['lûuk káa', 'ลูกค้า', ['customer', 'client'], 'n', ['work']],
  ['îi-meen', 'อีเมล', ['email'], 'n', ['work']],
  ['in-təə-nét', 'อินเทอร์เน็ต', ['internet'], 'n', ['work']],
  ['wép', 'เว็บ', ['web', 'website'], 'n', ['work']],
  ['kom-piw-dtəə', 'คอมพิวเตอร์', ['computer'], 'n', ['work']],
  ['dtaam', 'ตาม', ['follow', 'according to'], 'v', ['work']],
  ['wáng#2', 'วาง', ['put down', 'place', 'plan'], 'v', ['work']],
  ['wáng pεεn', 'วางแผน', ['to plan', 'make a plan'], 'v', ['work']],
  ['pεεn', 'แผน', ['plan'], 'n', ['work']],
  ['krom', 'กรม', ['department (gov)'], 'n', ['work']],
  ['bɔɔ-rí-sàt', 'บริษัท', ['company'], 'n', ['work']],
  ['ngən dụụan', 'เงินเดือน', ['salary'], 'n', ['work']],
  ['làa', 'ลา', ['take leave', 'day off'], 'v', ['work']],
  ['wan yùt', 'วันหยุด', ['holiday', 'day off'], 'n', ['work']],
  ['rian nǎng-sụ̌ụ', 'เรียนหนังสือ', ['study', 'be in school'], 'v', ['work']],
  ['krùu', 'ครู', ['teacher'], 'n', ['work']],
  ['nák-rian', 'นักเรียน', ['student'], 'n', ['work']],
  ['rɔɔng-rian', 'โรงเรียน', ['school'], 'n', ['work']],
  ['má-hǎa-wít-tá-yaa-lai', 'มหาวิทยาลัย', ['university'], 'n', ['work']],
  ['bai-ngaan', 'ใบงาน', ['worksheet'], 'n', ['work']],
  ['sɔ̌ɔp', 'สอบ', ['exam', 'to take an exam'], 'v', ['work']],
  ['pàan', 'ผ่าน', ['pass', 'to pass'], 'v', ['work']],
  ['dtòk', 'ตก', ['fail', 'fall'], 'v', ['work']],
])
