import { words } from '../build'

export default words(18, [
  ['nát', 'นัด', ['appointment', 'to make a date'], 'n', ['city']],
  ['kui', 'คุย', ['chat', 'to chat', 'talk'], 'v', ['city']],
  ['dtòk long', 'ตกลง', ['agree', 'deal'], 'v', ['city']],
  ['nát jəə', 'นัดเจอ', ['make a plan to meet'], 'v', ['city']],
  ['sà-tǎan-tîi', 'สถานที่', ['place', 'venue'], 'n', ['city']],
  ['bàa', 'บาร์', ['bar'], 'n', ['city']],
  ['ráan gaa-fεε', 'ร้านกาแฟ', ['cafe', 'coffee shop'], 'n', ['city']],
  ['roong nǎng', 'โรงหนัง', ['cinema', 'movie theatre'], 'n', ['city']],
  ['kâao sǎn', 'ข้าวสาร', ['Khao San'], 'n', ['city']],
  ['sì-lǒm', 'สีลม', ['Silom'], 'n', ['city']],
  ['sù-kǔm-wít', 'สุขุมวิท', ['Sukhumvit'], 'n', ['city']],
  ['jà-dtù-jàk', 'จตุจักร', ['Chatuchak'], 'n', ['city']],
  ['tεεo', 'แถว', ['area', 'row', 'neighbourhood'], 'n', ['city']],
  ['pûak', 'พวก', ['group', 'bunch'], 'n', ['city']],
  ['dtà-làat nát', 'ตลาดนัด', ['weekend market'], 'n', ['city']],
  ['kui lên', 'คุยเล่น', ['chat for fun'], 'v', ['city']],
  ['dtà-làat náam', 'ตลาดน้ำ', ['floating market'], 'n', ['city']],
  ['tîao glaang kụụn', 'เที่ยวกลางคืน', ['go out at night'], 'v', ['city']],
  ['nát wee-laa', 'นัดเวลา', ['set a time'], 'v', ['city']],
  ['yìam', 'เยี่ยม', ['visit', 'great'], 'v', ['city']],
  ['chom', 'ชม', ['appreciate', 'watch', 'praise'], 'v', ['city']],
  ['hǔa-rɔ́', 'หัวเราะ', ['laugh'], 'v', ['city']],
  ['dtὲng dtua', 'แต่งตัว', ['get dressed'], 'v', ['city']],
  ['gii-laa', 'กีฬา', ['sport', 'sports'], 'n', ['city']],
  ['lên gii-laa', 'เล่นกีฬา', ['play sports', 'do sport'], 'v', ['city']],
])
