import { words } from '../build'

export default words(3, [
  ['à-rai', 'อะไร', ['what'], 'q', ['question']],
  ['tîi-nǎi', 'ที่ไหน', ['where'], 'q', ['question']],
  ['nǎi', 'ไหน', ['which', 'where (casual)', 'where'], 'q', ['question'], 'bpai nǎi = where to. an nǎi = which one.'],
  ['mʉ̂a-rài', 'เมื่อไร', ['when'], 'q', ['question']],
  ['tam-mai', 'ทำไม', ['why'], 'q', ['question']],
  ['krai', 'ใคร', ['who', 'whom'], 'q', ['question']],
  ['yang-ngai', 'ยังไง', ['how', 'in what way'], 'q', ['question'], 'Spoken form of yàang-rai.'],
  ['yàang-rai', 'อย่างไร', ['how (formal)', 'how', 'in what manner'], 'q', ['question'], 'Written and formal. Spoken Thai uses yang-ngai.'],
  ['tâo-rài', 'เท่าไร', ['how much', 'how much (money)'], 'q', ['question']],
  ['gìi', 'กี่', ['how many'], 'q', ['question'], 'Always followed by a classifier: gìi kon, gìi bpii.'],
  ['rʉ̌ʉ', 'หรือ', ['or', 'or?', 'really?'], 'conj', ['question'], 'At the end of a sentence it asks for confirmation: kun bpai rʉ̌ʉ = oh, you are going?'],
  ['rʉ̌ʉ bplào', 'หรือเปล่า', ['or not', '(question) or not'], 'q', ['question'], 'kun chɔ̂ɔp rʉ̌ʉ bplào = do you like it or not.'],
  ['bplào', 'เปล่า', ['no', 'not at all', 'nothing', 'no (I am not)'], 'expr', ['yes-no'], 'The "no" answer to a rʉ̌ʉ bplào question.'],
  ['châi mái', 'ใช่ไหม', ['right?', 'is that right', 'isn’t it', 'correct?'], 'q', ['question']],
  ['lâ', 'ล่ะ', ['and (you)?', 'what about', 'and…?'], 'particle', ['question'], 'kun lâ = and you?'],
  ['bâang', 'บ้าง', ['some', 'any', '(what) sort of', 'a few'], 'particle', ['question'], 'Opens a question to a list: mii à-rai bâang = what things are there.'],
  ['jàak', 'จาก', ['from'], 'prep', []],
  ['bprà-têet', 'ประเทศ', ['country', 'nation'], 'n', ['place']],
  ['mʉang', 'เมือง', ['city', 'town', 'country (casual)'], 'n', ['place']],
  ['sà-bpeen', 'สเปน', ['Spain'], 'n', ['place']],
  ['kon sà-bpeen', 'คนสเปน', ['Spanish person', 'Spaniard', 'Spanish'], 'n', ['people']],
  ['aa-yú', 'อายุ', ['age'], 'n', []],
  ['bpii', 'ปี', ['year', 'years'], 'n', ['time']],
  ['roong-rεεm', 'โรงแรม', ['hotel'], 'n', ['place']],
  ['dtà-làat', 'ตลาด', ['market'], 'n', ['place']],
  ['ráan', 'ร้าน', ['shop', 'store', 'stall'], 'n', ['place']],
  ['ráan aa-hǎan', 'ร้านอาหาร', ['restaurant', 'food shop', 'eatery'], 'n', ['place']],
  ['an', 'อัน', ['one (thing)', 'piece', 'item', 'thing (classifier)'], 'clf', ['classifier'], 'Classifier for small things. an níi = this one.'],
  ['bàat', 'บาท', ['baht'], 'n', ['money']],
  ['kɔ̌ɔng kun', 'ของคุณ', ['your', 'yours'], 'pron', ['pronoun']],
  ['kɔ̌ɔng pǒm', 'ของผม', ['my, male speaker', 'my', 'mine', 'my (male speaker)'], 'pron', ['pronoun']],
  ['kɔ̌ɔng chǎn', 'ของฉัน', ['my, female speaker', 'my', 'mine', 'my (female speaker)'], 'pron', ['pronoun']],
  ['wâa', 'ว่า', ['that (complementizer)', 'that'], 'conj', [], 'mâi rúu wâa krai. Also "say that".'],
])
