import { words } from '../build'

export default words(26, [
  // what people do
  ['aa-chîip', 'อาชีพ', ['occupation', 'profession', 'a living'], 'n', ['job']],
  ['tá-hǎan', 'ทหาร', ['soldier', 'the army'], 'n', ['job']],
  ['pá-yaa-baan', 'พยาบาล', ['nurse'], 'n', ['job']],
  ['châang', 'ช่าง', ['technician', 'repairman', 'craftsman'], 'n', ['job'], 'The one you call when something is sǐa.'],
  ['tá-naai', 'ทนาย', ['lawyer'], 'n', ['job']],
  ['nák bin', 'นักบิน', ['pilot'], 'n', ['job']],
  ['pá-nák ngaan', 'พนักงาน', ['staff', 'employee'], 'n', ['job']],
  ['chaao naa', 'ชาวนา', ['rice farmer', 'farmer'], 'n', ['job']],
  ['pɔ̂ɔ káa', 'พ่อค้า', ['merchant', 'male vendor'], 'n', ['job']],
  ['mε̂ε káa', 'แม่ค้า', ['vendor', 'female vendor', 'market seller'], 'n', ['job']],
  ['jâo kɔ̌ɔng', 'เจ้าของ', ['owner'], 'n', ['job']],
  ['nák tú-rá-gìt', 'นักธุรกิจ', ['businessman', 'businessperson'], 'n', ['job']],
  ['sǐn-lá-bpin', 'ศิลปิน', ['artist'], 'n', ['job']],
  // saturday
  ['fút-bɔn', 'ฟุตบอล', ['football', 'soccer'], 'n', ['football']],
  ['bɔn', 'บอล', ['ball', 'the football'], 'n', ['football'], 'duu bɔn: watch the football.'],
  ['tiim', 'ทีม', ['team'], 'n', ['football']],
  ['nák dtὲ', 'นักเตะ', ['footballer', 'player'], 'n', ['football']],
  ['dtὲ', 'เตะ', ['kick', 'to kick'], 'v', ['football']],
  ['ying', 'ยิง', ['shoot', 'to shoot', 'fire'], 'v', ['football']],
  ['chá-ná', 'ชนะ', ['win', 'to win', 'beat'], 'v', ['football']],
  ['sà-mə̌ə', 'เสมอ', ['draw', 'a draw', 'tie'], 'v', ['football']],
  ['kὲng', 'แข่ง', ['compete', 'race', 'play against'], 'v', ['football']],
  ['chia', 'เชียร์', ['cheer', 'support', 'root for'], 'v', ['football']],
  ['sà-nǎam', 'สนาม', ['field', 'ground', 'pitch'], 'n', ['football']],
  ['gɔɔng nâa', 'กองหน้า', ['forward', 'striker'], 'n', ['football']],
  ['gɔɔng lǎng', 'กองหลัง', ['defender', 'the defence'], 'n', ['football']],
  ['pûu rák-sǎa bprà-dtuu', 'ผู้รักษาประตู', ['goalkeeper'], 'n', ['football'], 'Literally the one who keeps the door.'],
  ['lûuk tôot', 'ลูกโทษ', ['penalty'], 'n', ['football']],
  ['bai dεεng', 'ใบแดง', ['red card'], 'n', ['football']],
  // the small words that soften a sentence
  ['mâi kɔ̂i', 'ไม่ค่อย', ['not very', 'not really', 'hardly'], 'adv', ['degree'], 'mâi kɔ̂i chɔ̂ɔp: I do not really like it.'],
  ['gùap', 'เกือบ', ['almost', 'nearly'], 'adv', ['degree']],
  ['bprà-maan', 'ประมาณ', ['about', 'approximately', 'around'], 'adv', ['degree']],
  ['pɔɔ dii', 'พอดี', ['just right', 'exactly', 'it fits'], 'adv', ['degree']],
  ['baang tii', 'บางที', ['sometimes', 'maybe', 'perhaps'], 'adv', ['degree']],
  ['baang kráng', 'บางครั้ง', ['sometimes', 'now and then'], 'adv', ['degree']],
  ['tâo nán', 'เท่านั้น', ['only', 'that is all', 'no more than that'], 'adv', ['degree']],
  ['sùan mâak', 'ส่วนมาก', ['mostly', 'for the most part'], 'adv', ['degree']],
  ['kɔ̂i kɔ̂i', 'ค่อยๆ', ['gently', 'gradually', 'little by little'], 'adv', ['degree'], 'Doubled, with ๆ, the way cháa cháa is.'],
  ['tε̂εp', 'แทบ', ['barely', 'hardly', 'almost'], 'adv', ['degree']],
])
