import { words } from '../build'

export default words(6, [
  ['sáai', 'ซ้าย', ['left'], 'adj', ['direction']],
  ['kwǎa', 'ขวา', ['right'], 'adj', ['direction']],
  ['dtrong', 'ตรง', ['straight', 'straight ahead'], 'adv', ['direction']],
  ['líao', 'เลี้ยว', ['turn', 'to turn'], 'v', ['direction']],
  ['jɔ̀ɔt', 'จอด', ['stop', 'park', 'to stop (a vehicle)'], 'v', ['travel']],
  ['rót yon', 'รถยนต์', ['car', 'automobile'], 'n', ['travel']],
  ['rót fai', 'รถไฟ', ['train'], 'n', ['travel']],
  ['rót fai fáa', 'รถไฟฟ้า', ['skytrain', 'BTS', 'electric train'], 'n', ['travel']],
  ['rót mee', 'รถเมล์', ['bus'], 'n', ['travel']],
  ['rót dtuuk-dtuuk', 'รถตุ๊กตุ๊ก', ['tuk tuk', 'tuk-tuk'], 'n', ['travel']],
  ['tέk-sîi', 'แท็กซี่', ['taxi'], 'n', ['travel']],
  ['mó-dtəə-sai', 'มอเตอร์ไซค์', ['motorbike', 'motorcycle'], 'n', ['travel']],
  ['sá-taa-nii', 'สถานี', ['station'], 'n', ['place']],
  ['sà-nǎam bin', 'สนามบิน', ['airport'], 'n', ['place']],
  ['tà-nǒn', 'ถนน', ['road', 'street'], 'n', ['place']],
  ['soi', 'ซอย', ['alley', 'side street', 'soi'], 'n', ['place']],
  ['sà-pǎan', 'สะพาน', ['bridge'], 'n', ['place']],
  ['hùa-mòm', 'หัวมุม', ['corner'], 'n', ['place']],
  ['dtrong kâam', 'ตรงข้าม', ['opposite', 'across from'], 'prep', ['direction']],
  ['kâang', 'ข้าง', ['beside', 'side', 'next to'], 'prep', ['direction']],
  ['nâa', 'หน้า', ['in front', 'front', 'page'], 'n', ['direction']],
  ['lǎng', 'หลัง', ['behind', 'back', 'after'], 'n', ['direction']],
  ['bon', 'บน', ['on', 'above', 'up'], 'prep', ['direction']],
  ['lâang', 'ล่าง', ['below', 'down', 'lower'], 'adj', ['direction']],
  ['nai', 'ใน', ['in', 'inside'], 'prep', ['direction']],
  ['nɔ̂ɔk', 'นอก', ['outside', 'out'], 'prep', ['direction']],
  ['tàang', 'ทาง', ['way', 'path', 'route'], 'n', ['travel']],
  ['pεεn-tîi', 'แผนที่', ['map'], 'n', ['travel']],
  ['bpai tîi-nǎi', 'ไปที่ไหน', ['where to', 'go where'], 'expr', ['travel']],
  ['lǒng', 'ลง', ['get off', 'go down', 'descend'], 'v', ['travel']],
  ['kûn', 'ขึ้น', ['get on', 'go up', 'ascend'], 'v', ['travel']],
  ['pìan', 'เปลี่ยน', ['change', 'to change'], 'v', ['travel']],
  ['reo', 'เร็ว', ['fast', 'quick'], 'adj', []],
  ['tàang ɔ̀ɔk', 'ทางออก', ['exit', 'way out'], 'n', ['travel']],
  ['tàang kâo', 'ทางเข้า', ['entrance', 'way in'], 'n', ['travel']],
  ['sìi-yε̂εk', 'สี่แยก', ['intersection', 'crossroads'], 'n', ['place']],
  ['fai dεεng', 'ไฟแดง', ['red light'], 'n', ['travel']],
  ['bai kàp kìi', 'ใบขับขี่', ['driving licence', 'driver license'], 'n', ['travel']],
  ['dtìt', 'ติด', ['stuck', 'stuck in traffic', 'attached'], 'v', ['travel']],
  ['rót dtìt', 'รถติด', ['traffic jam', 'the traffic is bad'], 'expr', ['travel']],
])
